
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QuizSession` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model QuizSession
 * 
 */
export type QuizSessionModel = runtime.Types.Result.DefaultSelection<Prisma.$QuizSessionPayload>

export type AggregateQuizSession = {
  _count: QuizSessionCountAggregateOutputType | null
  _min: QuizSessionMinAggregateOutputType | null
  _max: QuizSessionMaxAggregateOutputType | null
}

export type QuizSessionMinAggregateOutputType = {
  id: string | null
  userId: string | null
  status: $Enums.QuizSessionStatus | null
  startedAt: Date | null
  completedAt: Date | null
}

export type QuizSessionMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  status: $Enums.QuizSessionStatus | null
  startedAt: Date | null
  completedAt: Date | null
}

export type QuizSessionCountAggregateOutputType = {
  id: number
  userId: number
  status: number
  startedAt: number
  completedAt: number
  _all: number
}


export type QuizSessionMinAggregateInputType = {
  id?: true
  userId?: true
  status?: true
  startedAt?: true
  completedAt?: true
}

export type QuizSessionMaxAggregateInputType = {
  id?: true
  userId?: true
  status?: true
  startedAt?: true
  completedAt?: true
}

export type QuizSessionCountAggregateInputType = {
  id?: true
  userId?: true
  status?: true
  startedAt?: true
  completedAt?: true
  _all?: true
}

export type QuizSessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizSession to aggregate.
   */
  where?: Prisma.QuizSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizSessions to fetch.
   */
  orderBy?: Prisma.QuizSessionOrderByWithRelationInput | Prisma.QuizSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuizSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuizSessions
  **/
  _count?: true | QuizSessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuizSessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuizSessionMaxAggregateInputType
}

export type GetQuizSessionAggregateType<T extends QuizSessionAggregateArgs> = {
      [P in keyof T & keyof AggregateQuizSession]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuizSession[P]>
    : Prisma.GetScalarType<T[P], AggregateQuizSession[P]>
}




export type QuizSessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuizSessionWhereInput
  orderBy?: Prisma.QuizSessionOrderByWithAggregationInput | Prisma.QuizSessionOrderByWithAggregationInput[]
  by: Prisma.QuizSessionScalarFieldEnum[] | Prisma.QuizSessionScalarFieldEnum
  having?: Prisma.QuizSessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuizSessionCountAggregateInputType | true
  _min?: QuizSessionMinAggregateInputType
  _max?: QuizSessionMaxAggregateInputType
}

export type QuizSessionGroupByOutputType = {
  id: string
  userId: string
  status: $Enums.QuizSessionStatus
  startedAt: Date
  completedAt: Date | null
  _count: QuizSessionCountAggregateOutputType | null
  _min: QuizSessionMinAggregateOutputType | null
  _max: QuizSessionMaxAggregateOutputType | null
}

export type GetQuizSessionGroupByPayload<T extends QuizSessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuizSessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuizSessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuizSessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuizSessionGroupByOutputType[P]>
      }
    >
  >



export type QuizSessionWhereInput = {
  AND?: Prisma.QuizSessionWhereInput | Prisma.QuizSessionWhereInput[]
  OR?: Prisma.QuizSessionWhereInput[]
  NOT?: Prisma.QuizSessionWhereInput | Prisma.QuizSessionWhereInput[]
  id?: Prisma.StringFilter<"QuizSession"> | string
  userId?: Prisma.StringFilter<"QuizSession"> | string
  status?: Prisma.EnumQuizSessionStatusFilter<"QuizSession"> | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFilter<"QuizSession"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"QuizSession"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  quizSessionQuestions?: Prisma.QuizSessionQuestionListRelationFilter
  responses?: Prisma.QuizResponseListRelationFilter
}

export type QuizSessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  quizSessionQuestions?: Prisma.QuizSessionQuestionOrderByRelationAggregateInput
  responses?: Prisma.QuizResponseOrderByRelationAggregateInput
}

export type QuizSessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.QuizSessionWhereInput | Prisma.QuizSessionWhereInput[]
  OR?: Prisma.QuizSessionWhereInput[]
  NOT?: Prisma.QuizSessionWhereInput | Prisma.QuizSessionWhereInput[]
  userId?: Prisma.StringFilter<"QuizSession"> | string
  status?: Prisma.EnumQuizSessionStatusFilter<"QuizSession"> | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFilter<"QuizSession"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"QuizSession"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  quizSessionQuestions?: Prisma.QuizSessionQuestionListRelationFilter
  responses?: Prisma.QuizResponseListRelationFilter
}, "id">

export type QuizSessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.QuizSessionCountOrderByAggregateInput
  _max?: Prisma.QuizSessionMaxOrderByAggregateInput
  _min?: Prisma.QuizSessionMinOrderByAggregateInput
}

export type QuizSessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuizSessionScalarWhereWithAggregatesInput | Prisma.QuizSessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuizSessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuizSessionScalarWhereWithAggregatesInput | Prisma.QuizSessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"QuizSession"> | string
  userId?: Prisma.StringWithAggregatesFilter<"QuizSession"> | string
  status?: Prisma.EnumQuizSessionStatusWithAggregatesFilter<"QuizSession"> | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeWithAggregatesFilter<"QuizSession"> | Date | string
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"QuizSession"> | Date | string | null
}

export type QuizSessionCreateInput = {
  id?: string
  status?: $Enums.QuizSessionStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutSessionsInput
  quizSessionQuestions?: Prisma.QuizSessionQuestionCreateNestedManyWithoutSessionInput
  responses?: Prisma.QuizResponseCreateNestedManyWithoutSessionInput
}

export type QuizSessionUncheckedCreateInput = {
  id?: string
  userId: string
  status?: $Enums.QuizSessionStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  quizSessionQuestions?: Prisma.QuizSessionQuestionUncheckedCreateNestedManyWithoutSessionInput
  responses?: Prisma.QuizResponseUncheckedCreateNestedManyWithoutSessionInput
}

export type QuizSessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumQuizSessionStatusFieldUpdateOperationsInput | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutSessionsNestedInput
  quizSessionQuestions?: Prisma.QuizSessionQuestionUpdateManyWithoutSessionNestedInput
  responses?: Prisma.QuizResponseUpdateManyWithoutSessionNestedInput
}

export type QuizSessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumQuizSessionStatusFieldUpdateOperationsInput | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  quizSessionQuestions?: Prisma.QuizSessionQuestionUncheckedUpdateManyWithoutSessionNestedInput
  responses?: Prisma.QuizResponseUncheckedUpdateManyWithoutSessionNestedInput
}

export type QuizSessionCreateManyInput = {
  id?: string
  userId: string
  status?: $Enums.QuizSessionStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
}

export type QuizSessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumQuizSessionStatusFieldUpdateOperationsInput | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type QuizSessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumQuizSessionStatusFieldUpdateOperationsInput | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type QuizSessionListRelationFilter = {
  every?: Prisma.QuizSessionWhereInput
  some?: Prisma.QuizSessionWhereInput
  none?: Prisma.QuizSessionWhereInput
}

export type QuizSessionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuizSessionScalarRelationFilter = {
  is?: Prisma.QuizSessionWhereInput
  isNot?: Prisma.QuizSessionWhereInput
}

export type QuizSessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type QuizSessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type QuizSessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type QuizSessionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.QuizSessionCreateWithoutUserInput, Prisma.QuizSessionUncheckedCreateWithoutUserInput> | Prisma.QuizSessionCreateWithoutUserInput[] | Prisma.QuizSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuizSessionCreateOrConnectWithoutUserInput | Prisma.QuizSessionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.QuizSessionCreateManyUserInputEnvelope
  connect?: Prisma.QuizSessionWhereUniqueInput | Prisma.QuizSessionWhereUniqueInput[]
}

export type QuizSessionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.QuizSessionCreateWithoutUserInput, Prisma.QuizSessionUncheckedCreateWithoutUserInput> | Prisma.QuizSessionCreateWithoutUserInput[] | Prisma.QuizSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuizSessionCreateOrConnectWithoutUserInput | Prisma.QuizSessionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.QuizSessionCreateManyUserInputEnvelope
  connect?: Prisma.QuizSessionWhereUniqueInput | Prisma.QuizSessionWhereUniqueInput[]
}

export type QuizSessionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.QuizSessionCreateWithoutUserInput, Prisma.QuizSessionUncheckedCreateWithoutUserInput> | Prisma.QuizSessionCreateWithoutUserInput[] | Prisma.QuizSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuizSessionCreateOrConnectWithoutUserInput | Prisma.QuizSessionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.QuizSessionUpsertWithWhereUniqueWithoutUserInput | Prisma.QuizSessionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.QuizSessionCreateManyUserInputEnvelope
  set?: Prisma.QuizSessionWhereUniqueInput | Prisma.QuizSessionWhereUniqueInput[]
  disconnect?: Prisma.QuizSessionWhereUniqueInput | Prisma.QuizSessionWhereUniqueInput[]
  delete?: Prisma.QuizSessionWhereUniqueInput | Prisma.QuizSessionWhereUniqueInput[]
  connect?: Prisma.QuizSessionWhereUniqueInput | Prisma.QuizSessionWhereUniqueInput[]
  update?: Prisma.QuizSessionUpdateWithWhereUniqueWithoutUserInput | Prisma.QuizSessionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.QuizSessionUpdateManyWithWhereWithoutUserInput | Prisma.QuizSessionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.QuizSessionScalarWhereInput | Prisma.QuizSessionScalarWhereInput[]
}

export type QuizSessionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.QuizSessionCreateWithoutUserInput, Prisma.QuizSessionUncheckedCreateWithoutUserInput> | Prisma.QuizSessionCreateWithoutUserInput[] | Prisma.QuizSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuizSessionCreateOrConnectWithoutUserInput | Prisma.QuizSessionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.QuizSessionUpsertWithWhereUniqueWithoutUserInput | Prisma.QuizSessionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.QuizSessionCreateManyUserInputEnvelope
  set?: Prisma.QuizSessionWhereUniqueInput | Prisma.QuizSessionWhereUniqueInput[]
  disconnect?: Prisma.QuizSessionWhereUniqueInput | Prisma.QuizSessionWhereUniqueInput[]
  delete?: Prisma.QuizSessionWhereUniqueInput | Prisma.QuizSessionWhereUniqueInput[]
  connect?: Prisma.QuizSessionWhereUniqueInput | Prisma.QuizSessionWhereUniqueInput[]
  update?: Prisma.QuizSessionUpdateWithWhereUniqueWithoutUserInput | Prisma.QuizSessionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.QuizSessionUpdateManyWithWhereWithoutUserInput | Prisma.QuizSessionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.QuizSessionScalarWhereInput | Prisma.QuizSessionScalarWhereInput[]
}

export type QuizSessionCreateNestedOneWithoutResponsesInput = {
  create?: Prisma.XOR<Prisma.QuizSessionCreateWithoutResponsesInput, Prisma.QuizSessionUncheckedCreateWithoutResponsesInput>
  connectOrCreate?: Prisma.QuizSessionCreateOrConnectWithoutResponsesInput
  connect?: Prisma.QuizSessionWhereUniqueInput
}

export type QuizSessionUpdateOneRequiredWithoutResponsesNestedInput = {
  create?: Prisma.XOR<Prisma.QuizSessionCreateWithoutResponsesInput, Prisma.QuizSessionUncheckedCreateWithoutResponsesInput>
  connectOrCreate?: Prisma.QuizSessionCreateOrConnectWithoutResponsesInput
  upsert?: Prisma.QuizSessionUpsertWithoutResponsesInput
  connect?: Prisma.QuizSessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.QuizSessionUpdateToOneWithWhereWithoutResponsesInput, Prisma.QuizSessionUpdateWithoutResponsesInput>, Prisma.QuizSessionUncheckedUpdateWithoutResponsesInput>
}

export type EnumQuizSessionStatusFieldUpdateOperationsInput = {
  set?: $Enums.QuizSessionStatus
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type QuizSessionCreateNestedOneWithoutQuizSessionQuestionsInput = {
  create?: Prisma.XOR<Prisma.QuizSessionCreateWithoutQuizSessionQuestionsInput, Prisma.QuizSessionUncheckedCreateWithoutQuizSessionQuestionsInput>
  connectOrCreate?: Prisma.QuizSessionCreateOrConnectWithoutQuizSessionQuestionsInput
  connect?: Prisma.QuizSessionWhereUniqueInput
}

export type QuizSessionUpdateOneRequiredWithoutQuizSessionQuestionsNestedInput = {
  create?: Prisma.XOR<Prisma.QuizSessionCreateWithoutQuizSessionQuestionsInput, Prisma.QuizSessionUncheckedCreateWithoutQuizSessionQuestionsInput>
  connectOrCreate?: Prisma.QuizSessionCreateOrConnectWithoutQuizSessionQuestionsInput
  upsert?: Prisma.QuizSessionUpsertWithoutQuizSessionQuestionsInput
  connect?: Prisma.QuizSessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.QuizSessionUpdateToOneWithWhereWithoutQuizSessionQuestionsInput, Prisma.QuizSessionUpdateWithoutQuizSessionQuestionsInput>, Prisma.QuizSessionUncheckedUpdateWithoutQuizSessionQuestionsInput>
}

export type QuizSessionCreateWithoutUserInput = {
  id?: string
  status?: $Enums.QuizSessionStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  quizSessionQuestions?: Prisma.QuizSessionQuestionCreateNestedManyWithoutSessionInput
  responses?: Prisma.QuizResponseCreateNestedManyWithoutSessionInput
}

export type QuizSessionUncheckedCreateWithoutUserInput = {
  id?: string
  status?: $Enums.QuizSessionStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  quizSessionQuestions?: Prisma.QuizSessionQuestionUncheckedCreateNestedManyWithoutSessionInput
  responses?: Prisma.QuizResponseUncheckedCreateNestedManyWithoutSessionInput
}

export type QuizSessionCreateOrConnectWithoutUserInput = {
  where: Prisma.QuizSessionWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizSessionCreateWithoutUserInput, Prisma.QuizSessionUncheckedCreateWithoutUserInput>
}

export type QuizSessionCreateManyUserInputEnvelope = {
  data: Prisma.QuizSessionCreateManyUserInput | Prisma.QuizSessionCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type QuizSessionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.QuizSessionWhereUniqueInput
  update: Prisma.XOR<Prisma.QuizSessionUpdateWithoutUserInput, Prisma.QuizSessionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.QuizSessionCreateWithoutUserInput, Prisma.QuizSessionUncheckedCreateWithoutUserInput>
}

export type QuizSessionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.QuizSessionWhereUniqueInput
  data: Prisma.XOR<Prisma.QuizSessionUpdateWithoutUserInput, Prisma.QuizSessionUncheckedUpdateWithoutUserInput>
}

export type QuizSessionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.QuizSessionScalarWhereInput
  data: Prisma.XOR<Prisma.QuizSessionUpdateManyMutationInput, Prisma.QuizSessionUncheckedUpdateManyWithoutUserInput>
}

export type QuizSessionScalarWhereInput = {
  AND?: Prisma.QuizSessionScalarWhereInput | Prisma.QuizSessionScalarWhereInput[]
  OR?: Prisma.QuizSessionScalarWhereInput[]
  NOT?: Prisma.QuizSessionScalarWhereInput | Prisma.QuizSessionScalarWhereInput[]
  id?: Prisma.StringFilter<"QuizSession"> | string
  userId?: Prisma.StringFilter<"QuizSession"> | string
  status?: Prisma.EnumQuizSessionStatusFilter<"QuizSession"> | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFilter<"QuizSession"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"QuizSession"> | Date | string | null
}

export type QuizSessionCreateWithoutResponsesInput = {
  id?: string
  status?: $Enums.QuizSessionStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutSessionsInput
  quizSessionQuestions?: Prisma.QuizSessionQuestionCreateNestedManyWithoutSessionInput
}

export type QuizSessionUncheckedCreateWithoutResponsesInput = {
  id?: string
  userId: string
  status?: $Enums.QuizSessionStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  quizSessionQuestions?: Prisma.QuizSessionQuestionUncheckedCreateNestedManyWithoutSessionInput
}

export type QuizSessionCreateOrConnectWithoutResponsesInput = {
  where: Prisma.QuizSessionWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizSessionCreateWithoutResponsesInput, Prisma.QuizSessionUncheckedCreateWithoutResponsesInput>
}

export type QuizSessionUpsertWithoutResponsesInput = {
  update: Prisma.XOR<Prisma.QuizSessionUpdateWithoutResponsesInput, Prisma.QuizSessionUncheckedUpdateWithoutResponsesInput>
  create: Prisma.XOR<Prisma.QuizSessionCreateWithoutResponsesInput, Prisma.QuizSessionUncheckedCreateWithoutResponsesInput>
  where?: Prisma.QuizSessionWhereInput
}

export type QuizSessionUpdateToOneWithWhereWithoutResponsesInput = {
  where?: Prisma.QuizSessionWhereInput
  data: Prisma.XOR<Prisma.QuizSessionUpdateWithoutResponsesInput, Prisma.QuizSessionUncheckedUpdateWithoutResponsesInput>
}

export type QuizSessionUpdateWithoutResponsesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumQuizSessionStatusFieldUpdateOperationsInput | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutSessionsNestedInput
  quizSessionQuestions?: Prisma.QuizSessionQuestionUpdateManyWithoutSessionNestedInput
}

export type QuizSessionUncheckedUpdateWithoutResponsesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumQuizSessionStatusFieldUpdateOperationsInput | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  quizSessionQuestions?: Prisma.QuizSessionQuestionUncheckedUpdateManyWithoutSessionNestedInput
}

export type QuizSessionCreateWithoutQuizSessionQuestionsInput = {
  id?: string
  status?: $Enums.QuizSessionStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutSessionsInput
  responses?: Prisma.QuizResponseCreateNestedManyWithoutSessionInput
}

export type QuizSessionUncheckedCreateWithoutQuizSessionQuestionsInput = {
  id?: string
  userId: string
  status?: $Enums.QuizSessionStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  responses?: Prisma.QuizResponseUncheckedCreateNestedManyWithoutSessionInput
}

export type QuizSessionCreateOrConnectWithoutQuizSessionQuestionsInput = {
  where: Prisma.QuizSessionWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizSessionCreateWithoutQuizSessionQuestionsInput, Prisma.QuizSessionUncheckedCreateWithoutQuizSessionQuestionsInput>
}

export type QuizSessionUpsertWithoutQuizSessionQuestionsInput = {
  update: Prisma.XOR<Prisma.QuizSessionUpdateWithoutQuizSessionQuestionsInput, Prisma.QuizSessionUncheckedUpdateWithoutQuizSessionQuestionsInput>
  create: Prisma.XOR<Prisma.QuizSessionCreateWithoutQuizSessionQuestionsInput, Prisma.QuizSessionUncheckedCreateWithoutQuizSessionQuestionsInput>
  where?: Prisma.QuizSessionWhereInput
}

export type QuizSessionUpdateToOneWithWhereWithoutQuizSessionQuestionsInput = {
  where?: Prisma.QuizSessionWhereInput
  data: Prisma.XOR<Prisma.QuizSessionUpdateWithoutQuizSessionQuestionsInput, Prisma.QuizSessionUncheckedUpdateWithoutQuizSessionQuestionsInput>
}

export type QuizSessionUpdateWithoutQuizSessionQuestionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumQuizSessionStatusFieldUpdateOperationsInput | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutSessionsNestedInput
  responses?: Prisma.QuizResponseUpdateManyWithoutSessionNestedInput
}

export type QuizSessionUncheckedUpdateWithoutQuizSessionQuestionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumQuizSessionStatusFieldUpdateOperationsInput | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  responses?: Prisma.QuizResponseUncheckedUpdateManyWithoutSessionNestedInput
}

export type QuizSessionCreateManyUserInput = {
  id?: string
  status?: $Enums.QuizSessionStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
}

export type QuizSessionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumQuizSessionStatusFieldUpdateOperationsInput | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  quizSessionQuestions?: Prisma.QuizSessionQuestionUpdateManyWithoutSessionNestedInput
  responses?: Prisma.QuizResponseUpdateManyWithoutSessionNestedInput
}

export type QuizSessionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumQuizSessionStatusFieldUpdateOperationsInput | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  quizSessionQuestions?: Prisma.QuizSessionQuestionUncheckedUpdateManyWithoutSessionNestedInput
  responses?: Prisma.QuizResponseUncheckedUpdateManyWithoutSessionNestedInput
}

export type QuizSessionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumQuizSessionStatusFieldUpdateOperationsInput | $Enums.QuizSessionStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type QuizSessionCountOutputType
 */

export type QuizSessionCountOutputType = {
  quizSessionQuestions: number
  responses: number
}

export type QuizSessionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  quizSessionQuestions?: boolean | QuizSessionCountOutputTypeCountQuizSessionQuestionsArgs
  responses?: boolean | QuizSessionCountOutputTypeCountResponsesArgs
}

/**
 * QuizSessionCountOutputType without action
 */
export type QuizSessionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionCountOutputType
   */
  select?: Prisma.QuizSessionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * QuizSessionCountOutputType without action
 */
export type QuizSessionCountOutputTypeCountQuizSessionQuestionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuizSessionQuestionWhereInput
}

/**
 * QuizSessionCountOutputType without action
 */
export type QuizSessionCountOutputTypeCountResponsesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuizResponseWhereInput
}


export type QuizSessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  status?: boolean
  startedAt?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  quizSessionQuestions?: boolean | Prisma.QuizSession$quizSessionQuestionsArgs<ExtArgs>
  responses?: boolean | Prisma.QuizSession$responsesArgs<ExtArgs>
  _count?: boolean | Prisma.QuizSessionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizSession"]>

export type QuizSessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  status?: boolean
  startedAt?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizSession"]>

export type QuizSessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  status?: boolean
  startedAt?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizSession"]>

export type QuizSessionSelectScalar = {
  id?: boolean
  userId?: boolean
  status?: boolean
  startedAt?: boolean
  completedAt?: boolean
}

export type QuizSessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "status" | "startedAt" | "completedAt", ExtArgs["result"]["quizSession"]>
export type QuizSessionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  quizSessionQuestions?: boolean | Prisma.QuizSession$quizSessionQuestionsArgs<ExtArgs>
  responses?: boolean | Prisma.QuizSession$responsesArgs<ExtArgs>
  _count?: boolean | Prisma.QuizSessionCountOutputTypeDefaultArgs<ExtArgs>
}
export type QuizSessionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type QuizSessionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $QuizSessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuizSession"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    quizSessionQuestions: Prisma.$QuizSessionQuestionPayload<ExtArgs>[]
    responses: Prisma.$QuizResponsePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    status: $Enums.QuizSessionStatus
    startedAt: Date
    completedAt: Date | null
  }, ExtArgs["result"]["quizSession"]>
  composites: {}
}

export type QuizSessionGetPayload<S extends boolean | null | undefined | QuizSessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload, S>

export type QuizSessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuizSessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuizSessionCountAggregateInputType | true
  }

export interface QuizSessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuizSession'], meta: { name: 'QuizSession' } }
  /**
   * Find zero or one QuizSession that matches the filter.
   * @param {QuizSessionFindUniqueArgs} args - Arguments to find a QuizSession
   * @example
   * // Get one QuizSession
   * const quizSession = await prisma.quizSession.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuizSessionFindUniqueArgs>(args: Prisma.SelectSubset<T, QuizSessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuizSessionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuizSession that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuizSessionFindUniqueOrThrowArgs} args - Arguments to find a QuizSession
   * @example
   * // Get one QuizSession
   * const quizSession = await prisma.quizSession.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuizSessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuizSessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizSessionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizSession that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionFindFirstArgs} args - Arguments to find a QuizSession
   * @example
   * // Get one QuizSession
   * const quizSession = await prisma.quizSession.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuizSessionFindFirstArgs>(args?: Prisma.SelectSubset<T, QuizSessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuizSessionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizSession that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionFindFirstOrThrowArgs} args - Arguments to find a QuizSession
   * @example
   * // Get one QuizSession
   * const quizSession = await prisma.quizSession.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuizSessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuizSessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizSessionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuizSessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuizSessions
   * const quizSessions = await prisma.quizSession.findMany()
   * 
   * // Get first 10 QuizSessions
   * const quizSessions = await prisma.quizSession.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const quizSessionWithIdOnly = await prisma.quizSession.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuizSessionFindManyArgs>(args?: Prisma.SelectSubset<T, QuizSessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuizSession.
   * @param {QuizSessionCreateArgs} args - Arguments to create a QuizSession.
   * @example
   * // Create one QuizSession
   * const QuizSession = await prisma.quizSession.create({
   *   data: {
   *     // ... data to create a QuizSession
   *   }
   * })
   * 
   */
  create<T extends QuizSessionCreateArgs>(args: Prisma.SelectSubset<T, QuizSessionCreateArgs<ExtArgs>>): Prisma.Prisma__QuizSessionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuizSessions.
   * @param {QuizSessionCreateManyArgs} args - Arguments to create many QuizSessions.
   * @example
   * // Create many QuizSessions
   * const quizSession = await prisma.quizSession.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuizSessionCreateManyArgs>(args?: Prisma.SelectSubset<T, QuizSessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuizSessions and returns the data saved in the database.
   * @param {QuizSessionCreateManyAndReturnArgs} args - Arguments to create many QuizSessions.
   * @example
   * // Create many QuizSessions
   * const quizSession = await prisma.quizSession.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuizSessions and only return the `id`
   * const quizSessionWithIdOnly = await prisma.quizSession.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuizSessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuizSessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuizSession.
   * @param {QuizSessionDeleteArgs} args - Arguments to delete one QuizSession.
   * @example
   * // Delete one QuizSession
   * const QuizSession = await prisma.quizSession.delete({
   *   where: {
   *     // ... filter to delete one QuizSession
   *   }
   * })
   * 
   */
  delete<T extends QuizSessionDeleteArgs>(args: Prisma.SelectSubset<T, QuizSessionDeleteArgs<ExtArgs>>): Prisma.Prisma__QuizSessionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuizSession.
   * @param {QuizSessionUpdateArgs} args - Arguments to update one QuizSession.
   * @example
   * // Update one QuizSession
   * const quizSession = await prisma.quizSession.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuizSessionUpdateArgs>(args: Prisma.SelectSubset<T, QuizSessionUpdateArgs<ExtArgs>>): Prisma.Prisma__QuizSessionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuizSessions.
   * @param {QuizSessionDeleteManyArgs} args - Arguments to filter QuizSessions to delete.
   * @example
   * // Delete a few QuizSessions
   * const { count } = await prisma.quizSession.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuizSessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuizSessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuizSessions
   * const quizSession = await prisma.quizSession.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuizSessionUpdateManyArgs>(args: Prisma.SelectSubset<T, QuizSessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizSessions and returns the data updated in the database.
   * @param {QuizSessionUpdateManyAndReturnArgs} args - Arguments to update many QuizSessions.
   * @example
   * // Update many QuizSessions
   * const quizSession = await prisma.quizSession.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuizSessions and only return the `id`
   * const quizSessionWithIdOnly = await prisma.quizSession.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuizSessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuizSessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuizSession.
   * @param {QuizSessionUpsertArgs} args - Arguments to update or create a QuizSession.
   * @example
   * // Update or create a QuizSession
   * const quizSession = await prisma.quizSession.upsert({
   *   create: {
   *     // ... data to create a QuizSession
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuizSession we want to update
   *   }
   * })
   */
  upsert<T extends QuizSessionUpsertArgs>(args: Prisma.SelectSubset<T, QuizSessionUpsertArgs<ExtArgs>>): Prisma.Prisma__QuizSessionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuizSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionCountArgs} args - Arguments to filter QuizSessions to count.
   * @example
   * // Count the number of QuizSessions
   * const count = await prisma.quizSession.count({
   *   where: {
   *     // ... the filter for the QuizSessions we want to count
   *   }
   * })
  **/
  count<T extends QuizSessionCountArgs>(
    args?: Prisma.Subset<T, QuizSessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuizSessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuizSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuizSessionAggregateArgs>(args: Prisma.Subset<T, QuizSessionAggregateArgs>): Prisma.PrismaPromise<GetQuizSessionAggregateType<T>>

  /**
   * Group by QuizSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuizSessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuizSessionGroupByArgs['orderBy'] }
      : { orderBy?: QuizSessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuizSessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuizSessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuizSession model
 */
readonly fields: QuizSessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuizSession.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuizSessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  quizSessionQuestions<T extends Prisma.QuizSession$quizSessionQuestionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuizSession$quizSessionQuestionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizSessionQuestionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  responses<T extends Prisma.QuizSession$responsesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuizSession$responsesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuizSession model
 */
export interface QuizSessionFieldRefs {
  readonly id: Prisma.FieldRef<"QuizSession", 'String'>
  readonly userId: Prisma.FieldRef<"QuizSession", 'String'>
  readonly status: Prisma.FieldRef<"QuizSession", 'QuizSessionStatus'>
  readonly startedAt: Prisma.FieldRef<"QuizSession", 'DateTime'>
  readonly completedAt: Prisma.FieldRef<"QuizSession", 'DateTime'>
}
    

// Custom InputTypes
/**
 * QuizSession findUnique
 */
export type QuizSessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSession
   */
  select?: Prisma.QuizSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSession
   */
  omit?: Prisma.QuizSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSession to fetch.
   */
  where: Prisma.QuizSessionWhereUniqueInput
}

/**
 * QuizSession findUniqueOrThrow
 */
export type QuizSessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSession
   */
  select?: Prisma.QuizSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSession
   */
  omit?: Prisma.QuizSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSession to fetch.
   */
  where: Prisma.QuizSessionWhereUniqueInput
}

/**
 * QuizSession findFirst
 */
export type QuizSessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSession
   */
  select?: Prisma.QuizSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSession
   */
  omit?: Prisma.QuizSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSession to fetch.
   */
  where?: Prisma.QuizSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizSessions to fetch.
   */
  orderBy?: Prisma.QuizSessionOrderByWithRelationInput | Prisma.QuizSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizSessions.
   */
  cursor?: Prisma.QuizSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizSessions.
   */
  distinct?: Prisma.QuizSessionScalarFieldEnum | Prisma.QuizSessionScalarFieldEnum[]
}

/**
 * QuizSession findFirstOrThrow
 */
export type QuizSessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSession
   */
  select?: Prisma.QuizSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSession
   */
  omit?: Prisma.QuizSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSession to fetch.
   */
  where?: Prisma.QuizSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizSessions to fetch.
   */
  orderBy?: Prisma.QuizSessionOrderByWithRelationInput | Prisma.QuizSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizSessions.
   */
  cursor?: Prisma.QuizSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizSessions.
   */
  distinct?: Prisma.QuizSessionScalarFieldEnum | Prisma.QuizSessionScalarFieldEnum[]
}

/**
 * QuizSession findMany
 */
export type QuizSessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSession
   */
  select?: Prisma.QuizSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSession
   */
  omit?: Prisma.QuizSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSessions to fetch.
   */
  where?: Prisma.QuizSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizSessions to fetch.
   */
  orderBy?: Prisma.QuizSessionOrderByWithRelationInput | Prisma.QuizSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuizSessions.
   */
  cursor?: Prisma.QuizSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizSessions.
   */
  distinct?: Prisma.QuizSessionScalarFieldEnum | Prisma.QuizSessionScalarFieldEnum[]
}

/**
 * QuizSession create
 */
export type QuizSessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSession
   */
  select?: Prisma.QuizSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSession
   */
  omit?: Prisma.QuizSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionInclude<ExtArgs> | null
  /**
   * The data needed to create a QuizSession.
   */
  data: Prisma.XOR<Prisma.QuizSessionCreateInput, Prisma.QuizSessionUncheckedCreateInput>
}

/**
 * QuizSession createMany
 */
export type QuizSessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuizSessions.
   */
  data: Prisma.QuizSessionCreateManyInput | Prisma.QuizSessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QuizSession createManyAndReturn
 */
export type QuizSessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSession
   */
  select?: Prisma.QuizSessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSession
   */
  omit?: Prisma.QuizSessionOmit<ExtArgs> | null
  /**
   * The data used to create many QuizSessions.
   */
  data: Prisma.QuizSessionCreateManyInput | Prisma.QuizSessionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuizSession update
 */
export type QuizSessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSession
   */
  select?: Prisma.QuizSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSession
   */
  omit?: Prisma.QuizSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionInclude<ExtArgs> | null
  /**
   * The data needed to update a QuizSession.
   */
  data: Prisma.XOR<Prisma.QuizSessionUpdateInput, Prisma.QuizSessionUncheckedUpdateInput>
  /**
   * Choose, which QuizSession to update.
   */
  where: Prisma.QuizSessionWhereUniqueInput
}

/**
 * QuizSession updateMany
 */
export type QuizSessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuizSessions.
   */
  data: Prisma.XOR<Prisma.QuizSessionUpdateManyMutationInput, Prisma.QuizSessionUncheckedUpdateManyInput>
  /**
   * Filter which QuizSessions to update
   */
  where?: Prisma.QuizSessionWhereInput
  /**
   * Limit how many QuizSessions to update.
   */
  limit?: number
}

/**
 * QuizSession updateManyAndReturn
 */
export type QuizSessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSession
   */
  select?: Prisma.QuizSessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSession
   */
  omit?: Prisma.QuizSessionOmit<ExtArgs> | null
  /**
   * The data used to update QuizSessions.
   */
  data: Prisma.XOR<Prisma.QuizSessionUpdateManyMutationInput, Prisma.QuizSessionUncheckedUpdateManyInput>
  /**
   * Filter which QuizSessions to update
   */
  where?: Prisma.QuizSessionWhereInput
  /**
   * Limit how many QuizSessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuizSession upsert
 */
export type QuizSessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSession
   */
  select?: Prisma.QuizSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSession
   */
  omit?: Prisma.QuizSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionInclude<ExtArgs> | null
  /**
   * The filter to search for the QuizSession to update in case it exists.
   */
  where: Prisma.QuizSessionWhereUniqueInput
  /**
   * In case the QuizSession found by the `where` argument doesn't exist, create a new QuizSession with this data.
   */
  create: Prisma.XOR<Prisma.QuizSessionCreateInput, Prisma.QuizSessionUncheckedCreateInput>
  /**
   * In case the QuizSession was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuizSessionUpdateInput, Prisma.QuizSessionUncheckedUpdateInput>
}

/**
 * QuizSession delete
 */
export type QuizSessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSession
   */
  select?: Prisma.QuizSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSession
   */
  omit?: Prisma.QuizSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionInclude<ExtArgs> | null
  /**
   * Filter which QuizSession to delete.
   */
  where: Prisma.QuizSessionWhereUniqueInput
}

/**
 * QuizSession deleteMany
 */
export type QuizSessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizSessions to delete
   */
  where?: Prisma.QuizSessionWhereInput
  /**
   * Limit how many QuizSessions to delete.
   */
  limit?: number
}

/**
 * QuizSession.quizSessionQuestions
 */
export type QuizSession$quizSessionQuestionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionQuestion
   */
  select?: Prisma.QuizSessionQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSessionQuestion
   */
  omit?: Prisma.QuizSessionQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionQuestionInclude<ExtArgs> | null
  where?: Prisma.QuizSessionQuestionWhereInput
  orderBy?: Prisma.QuizSessionQuestionOrderByWithRelationInput | Prisma.QuizSessionQuestionOrderByWithRelationInput[]
  cursor?: Prisma.QuizSessionQuestionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.QuizSessionQuestionScalarFieldEnum | Prisma.QuizSessionQuestionScalarFieldEnum[]
}

/**
 * QuizSession.responses
 */
export type QuizSession$responsesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponse
   */
  select?: Prisma.QuizResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponse
   */
  omit?: Prisma.QuizResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseInclude<ExtArgs> | null
  where?: Prisma.QuizResponseWhereInput
  orderBy?: Prisma.QuizResponseOrderByWithRelationInput | Prisma.QuizResponseOrderByWithRelationInput[]
  cursor?: Prisma.QuizResponseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.QuizResponseScalarFieldEnum | Prisma.QuizResponseScalarFieldEnum[]
}

/**
 * QuizSession without action
 */
export type QuizSessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSession
   */
  select?: Prisma.QuizSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSession
   */
  omit?: Prisma.QuizSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionInclude<ExtArgs> | null
}
