
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QuizSessionQuestion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model QuizSessionQuestion
 * 
 */
export type QuizSessionQuestionModel = runtime.Types.Result.DefaultSelection<Prisma.$QuizSessionQuestionPayload>

export type AggregateQuizSessionQuestion = {
  _count: QuizSessionQuestionCountAggregateOutputType | null
  _min: QuizSessionQuestionMinAggregateOutputType | null
  _max: QuizSessionQuestionMaxAggregateOutputType | null
}

export type QuizSessionQuestionMinAggregateOutputType = {
  sessionId: string | null
  questionId: string | null
}

export type QuizSessionQuestionMaxAggregateOutputType = {
  sessionId: string | null
  questionId: string | null
}

export type QuizSessionQuestionCountAggregateOutputType = {
  sessionId: number
  questionId: number
  _all: number
}


export type QuizSessionQuestionMinAggregateInputType = {
  sessionId?: true
  questionId?: true
}

export type QuizSessionQuestionMaxAggregateInputType = {
  sessionId?: true
  questionId?: true
}

export type QuizSessionQuestionCountAggregateInputType = {
  sessionId?: true
  questionId?: true
  _all?: true
}

export type QuizSessionQuestionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizSessionQuestion to aggregate.
   */
  where?: Prisma.QuizSessionQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizSessionQuestions to fetch.
   */
  orderBy?: Prisma.QuizSessionQuestionOrderByWithRelationInput | Prisma.QuizSessionQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuizSessionQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizSessionQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizSessionQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuizSessionQuestions
  **/
  _count?: true | QuizSessionQuestionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuizSessionQuestionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuizSessionQuestionMaxAggregateInputType
}

export type GetQuizSessionQuestionAggregateType<T extends QuizSessionQuestionAggregateArgs> = {
      [P in keyof T & keyof AggregateQuizSessionQuestion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuizSessionQuestion[P]>
    : Prisma.GetScalarType<T[P], AggregateQuizSessionQuestion[P]>
}




export type QuizSessionQuestionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuizSessionQuestionWhereInput
  orderBy?: Prisma.QuizSessionQuestionOrderByWithAggregationInput | Prisma.QuizSessionQuestionOrderByWithAggregationInput[]
  by: Prisma.QuizSessionQuestionScalarFieldEnum[] | Prisma.QuizSessionQuestionScalarFieldEnum
  having?: Prisma.QuizSessionQuestionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuizSessionQuestionCountAggregateInputType | true
  _min?: QuizSessionQuestionMinAggregateInputType
  _max?: QuizSessionQuestionMaxAggregateInputType
}

export type QuizSessionQuestionGroupByOutputType = {
  sessionId: string
  questionId: string
  _count: QuizSessionQuestionCountAggregateOutputType | null
  _min: QuizSessionQuestionMinAggregateOutputType | null
  _max: QuizSessionQuestionMaxAggregateOutputType | null
}

export type GetQuizSessionQuestionGroupByPayload<T extends QuizSessionQuestionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuizSessionQuestionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuizSessionQuestionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuizSessionQuestionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuizSessionQuestionGroupByOutputType[P]>
      }
    >
  >



export type QuizSessionQuestionWhereInput = {
  AND?: Prisma.QuizSessionQuestionWhereInput | Prisma.QuizSessionQuestionWhereInput[]
  OR?: Prisma.QuizSessionQuestionWhereInput[]
  NOT?: Prisma.QuizSessionQuestionWhereInput | Prisma.QuizSessionQuestionWhereInput[]
  sessionId?: Prisma.StringFilter<"QuizSessionQuestion"> | string
  questionId?: Prisma.StringFilter<"QuizSessionQuestion"> | string
  session?: Prisma.XOR<Prisma.QuizSessionScalarRelationFilter, Prisma.QuizSessionWhereInput>
  question?: Prisma.XOR<Prisma.QuestionScalarRelationFilter, Prisma.QuestionWhereInput>
}

export type QuizSessionQuestionOrderByWithRelationInput = {
  sessionId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  session?: Prisma.QuizSessionOrderByWithRelationInput
  question?: Prisma.QuestionOrderByWithRelationInput
}

export type QuizSessionQuestionWhereUniqueInput = Prisma.AtLeast<{
  sessionId_questionId?: Prisma.QuizSessionQuestionSessionIdQuestionIdCompoundUniqueInput
  AND?: Prisma.QuizSessionQuestionWhereInput | Prisma.QuizSessionQuestionWhereInput[]
  OR?: Prisma.QuizSessionQuestionWhereInput[]
  NOT?: Prisma.QuizSessionQuestionWhereInput | Prisma.QuizSessionQuestionWhereInput[]
  sessionId?: Prisma.StringFilter<"QuizSessionQuestion"> | string
  questionId?: Prisma.StringFilter<"QuizSessionQuestion"> | string
  session?: Prisma.XOR<Prisma.QuizSessionScalarRelationFilter, Prisma.QuizSessionWhereInput>
  question?: Prisma.XOR<Prisma.QuestionScalarRelationFilter, Prisma.QuestionWhereInput>
}, "sessionId_questionId">

export type QuizSessionQuestionOrderByWithAggregationInput = {
  sessionId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  _count?: Prisma.QuizSessionQuestionCountOrderByAggregateInput
  _max?: Prisma.QuizSessionQuestionMaxOrderByAggregateInput
  _min?: Prisma.QuizSessionQuestionMinOrderByAggregateInput
}

export type QuizSessionQuestionScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuizSessionQuestionScalarWhereWithAggregatesInput | Prisma.QuizSessionQuestionScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuizSessionQuestionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuizSessionQuestionScalarWhereWithAggregatesInput | Prisma.QuizSessionQuestionScalarWhereWithAggregatesInput[]
  sessionId?: Prisma.StringWithAggregatesFilter<"QuizSessionQuestion"> | string
  questionId?: Prisma.StringWithAggregatesFilter<"QuizSessionQuestion"> | string
}

export type QuizSessionQuestionCreateInput = {
  session: Prisma.QuizSessionCreateNestedOneWithoutQuizSessionQuestionsInput
  question: Prisma.QuestionCreateNestedOneWithoutQuizSessionQuestionsInput
}

export type QuizSessionQuestionUncheckedCreateInput = {
  sessionId: string
  questionId: string
}

export type QuizSessionQuestionUpdateInput = {
  session?: Prisma.QuizSessionUpdateOneRequiredWithoutQuizSessionQuestionsNestedInput
  question?: Prisma.QuestionUpdateOneRequiredWithoutQuizSessionQuestionsNestedInput
}

export type QuizSessionQuestionUncheckedUpdateInput = {
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type QuizSessionQuestionCreateManyInput = {
  sessionId: string
  questionId: string
}

export type QuizSessionQuestionUpdateManyMutationInput = {

}

export type QuizSessionQuestionUncheckedUpdateManyInput = {
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type QuizSessionQuestionListRelationFilter = {
  every?: Prisma.QuizSessionQuestionWhereInput
  some?: Prisma.QuizSessionQuestionWhereInput
  none?: Prisma.QuizSessionQuestionWhereInput
}

export type QuizSessionQuestionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuizSessionQuestionSessionIdQuestionIdCompoundUniqueInput = {
  sessionId: string
  questionId: string
}

export type QuizSessionQuestionCountOrderByAggregateInput = {
  sessionId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
}

export type QuizSessionQuestionMaxOrderByAggregateInput = {
  sessionId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
}

export type QuizSessionQuestionMinOrderByAggregateInput = {
  sessionId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
}

export type QuizSessionQuestionCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.QuizSessionQuestionCreateWithoutQuestionInput, Prisma.QuizSessionQuestionUncheckedCreateWithoutQuestionInput> | Prisma.QuizSessionQuestionCreateWithoutQuestionInput[] | Prisma.QuizSessionQuestionUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuizSessionQuestionCreateOrConnectWithoutQuestionInput | Prisma.QuizSessionQuestionCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.QuizSessionQuestionCreateManyQuestionInputEnvelope
  connect?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
}

export type QuizSessionQuestionUncheckedCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.QuizSessionQuestionCreateWithoutQuestionInput, Prisma.QuizSessionQuestionUncheckedCreateWithoutQuestionInput> | Prisma.QuizSessionQuestionCreateWithoutQuestionInput[] | Prisma.QuizSessionQuestionUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuizSessionQuestionCreateOrConnectWithoutQuestionInput | Prisma.QuizSessionQuestionCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.QuizSessionQuestionCreateManyQuestionInputEnvelope
  connect?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
}

export type QuizSessionQuestionUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.QuizSessionQuestionCreateWithoutQuestionInput, Prisma.QuizSessionQuestionUncheckedCreateWithoutQuestionInput> | Prisma.QuizSessionQuestionCreateWithoutQuestionInput[] | Prisma.QuizSessionQuestionUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuizSessionQuestionCreateOrConnectWithoutQuestionInput | Prisma.QuizSessionQuestionCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.QuizSessionQuestionUpsertWithWhereUniqueWithoutQuestionInput | Prisma.QuizSessionQuestionUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.QuizSessionQuestionCreateManyQuestionInputEnvelope
  set?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  disconnect?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  delete?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  connect?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  update?: Prisma.QuizSessionQuestionUpdateWithWhereUniqueWithoutQuestionInput | Prisma.QuizSessionQuestionUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.QuizSessionQuestionUpdateManyWithWhereWithoutQuestionInput | Prisma.QuizSessionQuestionUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.QuizSessionQuestionScalarWhereInput | Prisma.QuizSessionQuestionScalarWhereInput[]
}

export type QuizSessionQuestionUncheckedUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.QuizSessionQuestionCreateWithoutQuestionInput, Prisma.QuizSessionQuestionUncheckedCreateWithoutQuestionInput> | Prisma.QuizSessionQuestionCreateWithoutQuestionInput[] | Prisma.QuizSessionQuestionUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuizSessionQuestionCreateOrConnectWithoutQuestionInput | Prisma.QuizSessionQuestionCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.QuizSessionQuestionUpsertWithWhereUniqueWithoutQuestionInput | Prisma.QuizSessionQuestionUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.QuizSessionQuestionCreateManyQuestionInputEnvelope
  set?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  disconnect?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  delete?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  connect?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  update?: Prisma.QuizSessionQuestionUpdateWithWhereUniqueWithoutQuestionInput | Prisma.QuizSessionQuestionUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.QuizSessionQuestionUpdateManyWithWhereWithoutQuestionInput | Prisma.QuizSessionQuestionUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.QuizSessionQuestionScalarWhereInput | Prisma.QuizSessionQuestionScalarWhereInput[]
}

export type QuizSessionQuestionCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.QuizSessionQuestionCreateWithoutSessionInput, Prisma.QuizSessionQuestionUncheckedCreateWithoutSessionInput> | Prisma.QuizSessionQuestionCreateWithoutSessionInput[] | Prisma.QuizSessionQuestionUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.QuizSessionQuestionCreateOrConnectWithoutSessionInput | Prisma.QuizSessionQuestionCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.QuizSessionQuestionCreateManySessionInputEnvelope
  connect?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
}

export type QuizSessionQuestionUncheckedCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.QuizSessionQuestionCreateWithoutSessionInput, Prisma.QuizSessionQuestionUncheckedCreateWithoutSessionInput> | Prisma.QuizSessionQuestionCreateWithoutSessionInput[] | Prisma.QuizSessionQuestionUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.QuizSessionQuestionCreateOrConnectWithoutSessionInput | Prisma.QuizSessionQuestionCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.QuizSessionQuestionCreateManySessionInputEnvelope
  connect?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
}

export type QuizSessionQuestionUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.QuizSessionQuestionCreateWithoutSessionInput, Prisma.QuizSessionQuestionUncheckedCreateWithoutSessionInput> | Prisma.QuizSessionQuestionCreateWithoutSessionInput[] | Prisma.QuizSessionQuestionUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.QuizSessionQuestionCreateOrConnectWithoutSessionInput | Prisma.QuizSessionQuestionCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.QuizSessionQuestionUpsertWithWhereUniqueWithoutSessionInput | Prisma.QuizSessionQuestionUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.QuizSessionQuestionCreateManySessionInputEnvelope
  set?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  disconnect?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  delete?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  connect?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  update?: Prisma.QuizSessionQuestionUpdateWithWhereUniqueWithoutSessionInput | Prisma.QuizSessionQuestionUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.QuizSessionQuestionUpdateManyWithWhereWithoutSessionInput | Prisma.QuizSessionQuestionUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.QuizSessionQuestionScalarWhereInput | Prisma.QuizSessionQuestionScalarWhereInput[]
}

export type QuizSessionQuestionUncheckedUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.QuizSessionQuestionCreateWithoutSessionInput, Prisma.QuizSessionQuestionUncheckedCreateWithoutSessionInput> | Prisma.QuizSessionQuestionCreateWithoutSessionInput[] | Prisma.QuizSessionQuestionUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.QuizSessionQuestionCreateOrConnectWithoutSessionInput | Prisma.QuizSessionQuestionCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.QuizSessionQuestionUpsertWithWhereUniqueWithoutSessionInput | Prisma.QuizSessionQuestionUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.QuizSessionQuestionCreateManySessionInputEnvelope
  set?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  disconnect?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  delete?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  connect?: Prisma.QuizSessionQuestionWhereUniqueInput | Prisma.QuizSessionQuestionWhereUniqueInput[]
  update?: Prisma.QuizSessionQuestionUpdateWithWhereUniqueWithoutSessionInput | Prisma.QuizSessionQuestionUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.QuizSessionQuestionUpdateManyWithWhereWithoutSessionInput | Prisma.QuizSessionQuestionUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.QuizSessionQuestionScalarWhereInput | Prisma.QuizSessionQuestionScalarWhereInput[]
}

export type QuizSessionQuestionCreateWithoutQuestionInput = {
  session: Prisma.QuizSessionCreateNestedOneWithoutQuizSessionQuestionsInput
}

export type QuizSessionQuestionUncheckedCreateWithoutQuestionInput = {
  sessionId: string
}

export type QuizSessionQuestionCreateOrConnectWithoutQuestionInput = {
  where: Prisma.QuizSessionQuestionWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizSessionQuestionCreateWithoutQuestionInput, Prisma.QuizSessionQuestionUncheckedCreateWithoutQuestionInput>
}

export type QuizSessionQuestionCreateManyQuestionInputEnvelope = {
  data: Prisma.QuizSessionQuestionCreateManyQuestionInput | Prisma.QuizSessionQuestionCreateManyQuestionInput[]
  skipDuplicates?: boolean
}

export type QuizSessionQuestionUpsertWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.QuizSessionQuestionWhereUniqueInput
  update: Prisma.XOR<Prisma.QuizSessionQuestionUpdateWithoutQuestionInput, Prisma.QuizSessionQuestionUncheckedUpdateWithoutQuestionInput>
  create: Prisma.XOR<Prisma.QuizSessionQuestionCreateWithoutQuestionInput, Prisma.QuizSessionQuestionUncheckedCreateWithoutQuestionInput>
}

export type QuizSessionQuestionUpdateWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.QuizSessionQuestionWhereUniqueInput
  data: Prisma.XOR<Prisma.QuizSessionQuestionUpdateWithoutQuestionInput, Prisma.QuizSessionQuestionUncheckedUpdateWithoutQuestionInput>
}

export type QuizSessionQuestionUpdateManyWithWhereWithoutQuestionInput = {
  where: Prisma.QuizSessionQuestionScalarWhereInput
  data: Prisma.XOR<Prisma.QuizSessionQuestionUpdateManyMutationInput, Prisma.QuizSessionQuestionUncheckedUpdateManyWithoutQuestionInput>
}

export type QuizSessionQuestionScalarWhereInput = {
  AND?: Prisma.QuizSessionQuestionScalarWhereInput | Prisma.QuizSessionQuestionScalarWhereInput[]
  OR?: Prisma.QuizSessionQuestionScalarWhereInput[]
  NOT?: Prisma.QuizSessionQuestionScalarWhereInput | Prisma.QuizSessionQuestionScalarWhereInput[]
  sessionId?: Prisma.StringFilter<"QuizSessionQuestion"> | string
  questionId?: Prisma.StringFilter<"QuizSessionQuestion"> | string
}

export type QuizSessionQuestionCreateWithoutSessionInput = {
  question: Prisma.QuestionCreateNestedOneWithoutQuizSessionQuestionsInput
}

export type QuizSessionQuestionUncheckedCreateWithoutSessionInput = {
  questionId: string
}

export type QuizSessionQuestionCreateOrConnectWithoutSessionInput = {
  where: Prisma.QuizSessionQuestionWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizSessionQuestionCreateWithoutSessionInput, Prisma.QuizSessionQuestionUncheckedCreateWithoutSessionInput>
}

export type QuizSessionQuestionCreateManySessionInputEnvelope = {
  data: Prisma.QuizSessionQuestionCreateManySessionInput | Prisma.QuizSessionQuestionCreateManySessionInput[]
  skipDuplicates?: boolean
}

export type QuizSessionQuestionUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.QuizSessionQuestionWhereUniqueInput
  update: Prisma.XOR<Prisma.QuizSessionQuestionUpdateWithoutSessionInput, Prisma.QuizSessionQuestionUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.QuizSessionQuestionCreateWithoutSessionInput, Prisma.QuizSessionQuestionUncheckedCreateWithoutSessionInput>
}

export type QuizSessionQuestionUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.QuizSessionQuestionWhereUniqueInput
  data: Prisma.XOR<Prisma.QuizSessionQuestionUpdateWithoutSessionInput, Prisma.QuizSessionQuestionUncheckedUpdateWithoutSessionInput>
}

export type QuizSessionQuestionUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.QuizSessionQuestionScalarWhereInput
  data: Prisma.XOR<Prisma.QuizSessionQuestionUpdateManyMutationInput, Prisma.QuizSessionQuestionUncheckedUpdateManyWithoutSessionInput>
}

export type QuizSessionQuestionCreateManyQuestionInput = {
  sessionId: string
}

export type QuizSessionQuestionUpdateWithoutQuestionInput = {
  session?: Prisma.QuizSessionUpdateOneRequiredWithoutQuizSessionQuestionsNestedInput
}

export type QuizSessionQuestionUncheckedUpdateWithoutQuestionInput = {
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type QuizSessionQuestionUncheckedUpdateManyWithoutQuestionInput = {
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type QuizSessionQuestionCreateManySessionInput = {
  questionId: string
}

export type QuizSessionQuestionUpdateWithoutSessionInput = {
  question?: Prisma.QuestionUpdateOneRequiredWithoutQuizSessionQuestionsNestedInput
}

export type QuizSessionQuestionUncheckedUpdateWithoutSessionInput = {
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type QuizSessionQuestionUncheckedUpdateManyWithoutSessionInput = {
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type QuizSessionQuestionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  sessionId?: boolean
  questionId?: boolean
  session?: boolean | Prisma.QuizSessionDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizSessionQuestion"]>

export type QuizSessionQuestionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  sessionId?: boolean
  questionId?: boolean
  session?: boolean | Prisma.QuizSessionDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizSessionQuestion"]>

export type QuizSessionQuestionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  sessionId?: boolean
  questionId?: boolean
  session?: boolean | Prisma.QuizSessionDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizSessionQuestion"]>

export type QuizSessionQuestionSelectScalar = {
  sessionId?: boolean
  questionId?: boolean
}

export type QuizSessionQuestionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"sessionId" | "questionId", ExtArgs["result"]["quizSessionQuestion"]>
export type QuizSessionQuestionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.QuizSessionDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}
export type QuizSessionQuestionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.QuizSessionDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}
export type QuizSessionQuestionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.QuizSessionDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}

export type $QuizSessionQuestionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuizSessionQuestion"
  objects: {
    session: Prisma.$QuizSessionPayload<ExtArgs>
    question: Prisma.$QuestionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    sessionId: string
    questionId: string
  }, ExtArgs["result"]["quizSessionQuestion"]>
  composites: {}
}

export type QuizSessionQuestionGetPayload<S extends boolean | null | undefined | QuizSessionQuestionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuizSessionQuestionPayload, S>

export type QuizSessionQuestionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuizSessionQuestionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuizSessionQuestionCountAggregateInputType | true
  }

export interface QuizSessionQuestionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuizSessionQuestion'], meta: { name: 'QuizSessionQuestion' } }
  /**
   * Find zero or one QuizSessionQuestion that matches the filter.
   * @param {QuizSessionQuestionFindUniqueArgs} args - Arguments to find a QuizSessionQuestion
   * @example
   * // Get one QuizSessionQuestion
   * const quizSessionQuestion = await prisma.quizSessionQuestion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuizSessionQuestionFindUniqueArgs>(args: Prisma.SelectSubset<T, QuizSessionQuestionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuizSessionQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionQuestionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuizSessionQuestion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuizSessionQuestionFindUniqueOrThrowArgs} args - Arguments to find a QuizSessionQuestion
   * @example
   * // Get one QuizSessionQuestion
   * const quizSessionQuestion = await prisma.quizSessionQuestion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuizSessionQuestionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuizSessionQuestionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizSessionQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionQuestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizSessionQuestion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionQuestionFindFirstArgs} args - Arguments to find a QuizSessionQuestion
   * @example
   * // Get one QuizSessionQuestion
   * const quizSessionQuestion = await prisma.quizSessionQuestion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuizSessionQuestionFindFirstArgs>(args?: Prisma.SelectSubset<T, QuizSessionQuestionFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuizSessionQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionQuestionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizSessionQuestion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionQuestionFindFirstOrThrowArgs} args - Arguments to find a QuizSessionQuestion
   * @example
   * // Get one QuizSessionQuestion
   * const quizSessionQuestion = await prisma.quizSessionQuestion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuizSessionQuestionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuizSessionQuestionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizSessionQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionQuestionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuizSessionQuestions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionQuestionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuizSessionQuestions
   * const quizSessionQuestions = await prisma.quizSessionQuestion.findMany()
   * 
   * // Get first 10 QuizSessionQuestions
   * const quizSessionQuestions = await prisma.quizSessionQuestion.findMany({ take: 10 })
   * 
   * // Only select the `sessionId`
   * const quizSessionQuestionWithSessionIdOnly = await prisma.quizSessionQuestion.findMany({ select: { sessionId: true } })
   * 
   */
  findMany<T extends QuizSessionQuestionFindManyArgs>(args?: Prisma.SelectSubset<T, QuizSessionQuestionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizSessionQuestionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuizSessionQuestion.
   * @param {QuizSessionQuestionCreateArgs} args - Arguments to create a QuizSessionQuestion.
   * @example
   * // Create one QuizSessionQuestion
   * const QuizSessionQuestion = await prisma.quizSessionQuestion.create({
   *   data: {
   *     // ... data to create a QuizSessionQuestion
   *   }
   * })
   * 
   */
  create<T extends QuizSessionQuestionCreateArgs>(args: Prisma.SelectSubset<T, QuizSessionQuestionCreateArgs<ExtArgs>>): Prisma.Prisma__QuizSessionQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionQuestionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuizSessionQuestions.
   * @param {QuizSessionQuestionCreateManyArgs} args - Arguments to create many QuizSessionQuestions.
   * @example
   * // Create many QuizSessionQuestions
   * const quizSessionQuestion = await prisma.quizSessionQuestion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuizSessionQuestionCreateManyArgs>(args?: Prisma.SelectSubset<T, QuizSessionQuestionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuizSessionQuestions and returns the data saved in the database.
   * @param {QuizSessionQuestionCreateManyAndReturnArgs} args - Arguments to create many QuizSessionQuestions.
   * @example
   * // Create many QuizSessionQuestions
   * const quizSessionQuestion = await prisma.quizSessionQuestion.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuizSessionQuestions and only return the `sessionId`
   * const quizSessionQuestionWithSessionIdOnly = await prisma.quizSessionQuestion.createManyAndReturn({
   *   select: { sessionId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuizSessionQuestionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuizSessionQuestionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizSessionQuestionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuizSessionQuestion.
   * @param {QuizSessionQuestionDeleteArgs} args - Arguments to delete one QuizSessionQuestion.
   * @example
   * // Delete one QuizSessionQuestion
   * const QuizSessionQuestion = await prisma.quizSessionQuestion.delete({
   *   where: {
   *     // ... filter to delete one QuizSessionQuestion
   *   }
   * })
   * 
   */
  delete<T extends QuizSessionQuestionDeleteArgs>(args: Prisma.SelectSubset<T, QuizSessionQuestionDeleteArgs<ExtArgs>>): Prisma.Prisma__QuizSessionQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionQuestionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuizSessionQuestion.
   * @param {QuizSessionQuestionUpdateArgs} args - Arguments to update one QuizSessionQuestion.
   * @example
   * // Update one QuizSessionQuestion
   * const quizSessionQuestion = await prisma.quizSessionQuestion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuizSessionQuestionUpdateArgs>(args: Prisma.SelectSubset<T, QuizSessionQuestionUpdateArgs<ExtArgs>>): Prisma.Prisma__QuizSessionQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionQuestionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuizSessionQuestions.
   * @param {QuizSessionQuestionDeleteManyArgs} args - Arguments to filter QuizSessionQuestions to delete.
   * @example
   * // Delete a few QuizSessionQuestions
   * const { count } = await prisma.quizSessionQuestion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuizSessionQuestionDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuizSessionQuestionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizSessionQuestions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionQuestionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuizSessionQuestions
   * const quizSessionQuestion = await prisma.quizSessionQuestion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuizSessionQuestionUpdateManyArgs>(args: Prisma.SelectSubset<T, QuizSessionQuestionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizSessionQuestions and returns the data updated in the database.
   * @param {QuizSessionQuestionUpdateManyAndReturnArgs} args - Arguments to update many QuizSessionQuestions.
   * @example
   * // Update many QuizSessionQuestions
   * const quizSessionQuestion = await prisma.quizSessionQuestion.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuizSessionQuestions and only return the `sessionId`
   * const quizSessionQuestionWithSessionIdOnly = await prisma.quizSessionQuestion.updateManyAndReturn({
   *   select: { sessionId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuizSessionQuestionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuizSessionQuestionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizSessionQuestionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuizSessionQuestion.
   * @param {QuizSessionQuestionUpsertArgs} args - Arguments to update or create a QuizSessionQuestion.
   * @example
   * // Update or create a QuizSessionQuestion
   * const quizSessionQuestion = await prisma.quizSessionQuestion.upsert({
   *   create: {
   *     // ... data to create a QuizSessionQuestion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuizSessionQuestion we want to update
   *   }
   * })
   */
  upsert<T extends QuizSessionQuestionUpsertArgs>(args: Prisma.SelectSubset<T, QuizSessionQuestionUpsertArgs<ExtArgs>>): Prisma.Prisma__QuizSessionQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionQuestionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuizSessionQuestions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionQuestionCountArgs} args - Arguments to filter QuizSessionQuestions to count.
   * @example
   * // Count the number of QuizSessionQuestions
   * const count = await prisma.quizSessionQuestion.count({
   *   where: {
   *     // ... the filter for the QuizSessionQuestions we want to count
   *   }
   * })
  **/
  count<T extends QuizSessionQuestionCountArgs>(
    args?: Prisma.Subset<T, QuizSessionQuestionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuizSessionQuestionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuizSessionQuestion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionQuestionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuizSessionQuestionAggregateArgs>(args: Prisma.Subset<T, QuizSessionQuestionAggregateArgs>): Prisma.PrismaPromise<GetQuizSessionQuestionAggregateType<T>>

  /**
   * Group by QuizSessionQuestion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizSessionQuestionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuizSessionQuestionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuizSessionQuestionGroupByArgs['orderBy'] }
      : { orderBy?: QuizSessionQuestionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuizSessionQuestionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuizSessionQuestionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuizSessionQuestion model
 */
readonly fields: QuizSessionQuestionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuizSessionQuestion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuizSessionQuestionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  session<T extends Prisma.QuizSessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuizSessionDefaultArgs<ExtArgs>>): Prisma.Prisma__QuizSessionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  question<T extends Prisma.QuestionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuestionDefaultArgs<ExtArgs>>): Prisma.Prisma__QuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuizSessionQuestion model
 */
export interface QuizSessionQuestionFieldRefs {
  readonly sessionId: Prisma.FieldRef<"QuizSessionQuestion", 'String'>
  readonly questionId: Prisma.FieldRef<"QuizSessionQuestion", 'String'>
}
    

// Custom InputTypes
/**
 * QuizSessionQuestion findUnique
 */
export type QuizSessionQuestionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionQuestion
   */
  select?: Prisma.QuizSessionQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSessionQuestion
   */
  omit?: Prisma.QuizSessionQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSessionQuestion to fetch.
   */
  where: Prisma.QuizSessionQuestionWhereUniqueInput
}

/**
 * QuizSessionQuestion findUniqueOrThrow
 */
export type QuizSessionQuestionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionQuestion
   */
  select?: Prisma.QuizSessionQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSessionQuestion
   */
  omit?: Prisma.QuizSessionQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSessionQuestion to fetch.
   */
  where: Prisma.QuizSessionQuestionWhereUniqueInput
}

/**
 * QuizSessionQuestion findFirst
 */
export type QuizSessionQuestionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionQuestion
   */
  select?: Prisma.QuizSessionQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSessionQuestion
   */
  omit?: Prisma.QuizSessionQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSessionQuestion to fetch.
   */
  where?: Prisma.QuizSessionQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizSessionQuestions to fetch.
   */
  orderBy?: Prisma.QuizSessionQuestionOrderByWithRelationInput | Prisma.QuizSessionQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizSessionQuestions.
   */
  cursor?: Prisma.QuizSessionQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizSessionQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizSessionQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizSessionQuestions.
   */
  distinct?: Prisma.QuizSessionQuestionScalarFieldEnum | Prisma.QuizSessionQuestionScalarFieldEnum[]
}

/**
 * QuizSessionQuestion findFirstOrThrow
 */
export type QuizSessionQuestionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionQuestion
   */
  select?: Prisma.QuizSessionQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSessionQuestion
   */
  omit?: Prisma.QuizSessionQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSessionQuestion to fetch.
   */
  where?: Prisma.QuizSessionQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizSessionQuestions to fetch.
   */
  orderBy?: Prisma.QuizSessionQuestionOrderByWithRelationInput | Prisma.QuizSessionQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizSessionQuestions.
   */
  cursor?: Prisma.QuizSessionQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizSessionQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizSessionQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizSessionQuestions.
   */
  distinct?: Prisma.QuizSessionQuestionScalarFieldEnum | Prisma.QuizSessionQuestionScalarFieldEnum[]
}

/**
 * QuizSessionQuestion findMany
 */
export type QuizSessionQuestionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionQuestion
   */
  select?: Prisma.QuizSessionQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSessionQuestion
   */
  omit?: Prisma.QuizSessionQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuizSessionQuestions to fetch.
   */
  where?: Prisma.QuizSessionQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizSessionQuestions to fetch.
   */
  orderBy?: Prisma.QuizSessionQuestionOrderByWithRelationInput | Prisma.QuizSessionQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuizSessionQuestions.
   */
  cursor?: Prisma.QuizSessionQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizSessionQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizSessionQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizSessionQuestions.
   */
  distinct?: Prisma.QuizSessionQuestionScalarFieldEnum | Prisma.QuizSessionQuestionScalarFieldEnum[]
}

/**
 * QuizSessionQuestion create
 */
export type QuizSessionQuestionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionQuestion
   */
  select?: Prisma.QuizSessionQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSessionQuestion
   */
  omit?: Prisma.QuizSessionQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionQuestionInclude<ExtArgs> | null
  /**
   * The data needed to create a QuizSessionQuestion.
   */
  data: Prisma.XOR<Prisma.QuizSessionQuestionCreateInput, Prisma.QuizSessionQuestionUncheckedCreateInput>
}

/**
 * QuizSessionQuestion createMany
 */
export type QuizSessionQuestionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuizSessionQuestions.
   */
  data: Prisma.QuizSessionQuestionCreateManyInput | Prisma.QuizSessionQuestionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QuizSessionQuestion createManyAndReturn
 */
export type QuizSessionQuestionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionQuestion
   */
  select?: Prisma.QuizSessionQuestionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSessionQuestion
   */
  omit?: Prisma.QuizSessionQuestionOmit<ExtArgs> | null
  /**
   * The data used to create many QuizSessionQuestions.
   */
  data: Prisma.QuizSessionQuestionCreateManyInput | Prisma.QuizSessionQuestionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionQuestionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuizSessionQuestion update
 */
export type QuizSessionQuestionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionQuestion
   */
  select?: Prisma.QuizSessionQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSessionQuestion
   */
  omit?: Prisma.QuizSessionQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionQuestionInclude<ExtArgs> | null
  /**
   * The data needed to update a QuizSessionQuestion.
   */
  data: Prisma.XOR<Prisma.QuizSessionQuestionUpdateInput, Prisma.QuizSessionQuestionUncheckedUpdateInput>
  /**
   * Choose, which QuizSessionQuestion to update.
   */
  where: Prisma.QuizSessionQuestionWhereUniqueInput
}

/**
 * QuizSessionQuestion updateMany
 */
export type QuizSessionQuestionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuizSessionQuestions.
   */
  data: Prisma.XOR<Prisma.QuizSessionQuestionUpdateManyMutationInput, Prisma.QuizSessionQuestionUncheckedUpdateManyInput>
  /**
   * Filter which QuizSessionQuestions to update
   */
  where?: Prisma.QuizSessionQuestionWhereInput
  /**
   * Limit how many QuizSessionQuestions to update.
   */
  limit?: number
}

/**
 * QuizSessionQuestion updateManyAndReturn
 */
export type QuizSessionQuestionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionQuestion
   */
  select?: Prisma.QuizSessionQuestionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSessionQuestion
   */
  omit?: Prisma.QuizSessionQuestionOmit<ExtArgs> | null
  /**
   * The data used to update QuizSessionQuestions.
   */
  data: Prisma.XOR<Prisma.QuizSessionQuestionUpdateManyMutationInput, Prisma.QuizSessionQuestionUncheckedUpdateManyInput>
  /**
   * Filter which QuizSessionQuestions to update
   */
  where?: Prisma.QuizSessionQuestionWhereInput
  /**
   * Limit how many QuizSessionQuestions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionQuestionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuizSessionQuestion upsert
 */
export type QuizSessionQuestionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionQuestion
   */
  select?: Prisma.QuizSessionQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSessionQuestion
   */
  omit?: Prisma.QuizSessionQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionQuestionInclude<ExtArgs> | null
  /**
   * The filter to search for the QuizSessionQuestion to update in case it exists.
   */
  where: Prisma.QuizSessionQuestionWhereUniqueInput
  /**
   * In case the QuizSessionQuestion found by the `where` argument doesn't exist, create a new QuizSessionQuestion with this data.
   */
  create: Prisma.XOR<Prisma.QuizSessionQuestionCreateInput, Prisma.QuizSessionQuestionUncheckedCreateInput>
  /**
   * In case the QuizSessionQuestion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuizSessionQuestionUpdateInput, Prisma.QuizSessionQuestionUncheckedUpdateInput>
}

/**
 * QuizSessionQuestion delete
 */
export type QuizSessionQuestionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionQuestion
   */
  select?: Prisma.QuizSessionQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSessionQuestion
   */
  omit?: Prisma.QuizSessionQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionQuestionInclude<ExtArgs> | null
  /**
   * Filter which QuizSessionQuestion to delete.
   */
  where: Prisma.QuizSessionQuestionWhereUniqueInput
}

/**
 * QuizSessionQuestion deleteMany
 */
export type QuizSessionQuestionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizSessionQuestions to delete
   */
  where?: Prisma.QuizSessionQuestionWhereInput
  /**
   * Limit how many QuizSessionQuestions to delete.
   */
  limit?: number
}

/**
 * QuizSessionQuestion without action
 */
export type QuizSessionQuestionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizSessionQuestion
   */
  select?: Prisma.QuizSessionQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizSessionQuestion
   */
  omit?: Prisma.QuizSessionQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizSessionQuestionInclude<ExtArgs> | null
}
