
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QuizResponse` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model QuizResponse
 * 
 */
export type QuizResponseModel = runtime.Types.Result.DefaultSelection<Prisma.$QuizResponsePayload>

export type AggregateQuizResponse = {
  _count: QuizResponseCountAggregateOutputType | null
  _avg: QuizResponseAvgAggregateOutputType | null
  _sum: QuizResponseSumAggregateOutputType | null
  _min: QuizResponseMinAggregateOutputType | null
  _max: QuizResponseMaxAggregateOutputType | null
}

export type QuizResponseAvgAggregateOutputType = {
  score: number | null
}

export type QuizResponseSumAggregateOutputType = {
  score: number | null
}

export type QuizResponseMinAggregateOutputType = {
  id: string | null
  sessionId: string | null
  questionId: string | null
  textAnswer: string | null
  isCorrect: boolean | null
  score: number | null
  feedback: string | null
  answeredAt: Date | null
}

export type QuizResponseMaxAggregateOutputType = {
  id: string | null
  sessionId: string | null
  questionId: string | null
  textAnswer: string | null
  isCorrect: boolean | null
  score: number | null
  feedback: string | null
  answeredAt: Date | null
}

export type QuizResponseCountAggregateOutputType = {
  id: number
  sessionId: number
  questionId: number
  textAnswer: number
  isCorrect: number
  score: number
  feedback: number
  answeredAt: number
  _all: number
}


export type QuizResponseAvgAggregateInputType = {
  score?: true
}

export type QuizResponseSumAggregateInputType = {
  score?: true
}

export type QuizResponseMinAggregateInputType = {
  id?: true
  sessionId?: true
  questionId?: true
  textAnswer?: true
  isCorrect?: true
  score?: true
  feedback?: true
  answeredAt?: true
}

export type QuizResponseMaxAggregateInputType = {
  id?: true
  sessionId?: true
  questionId?: true
  textAnswer?: true
  isCorrect?: true
  score?: true
  feedback?: true
  answeredAt?: true
}

export type QuizResponseCountAggregateInputType = {
  id?: true
  sessionId?: true
  questionId?: true
  textAnswer?: true
  isCorrect?: true
  score?: true
  feedback?: true
  answeredAt?: true
  _all?: true
}

export type QuizResponseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizResponse to aggregate.
   */
  where?: Prisma.QuizResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizResponses to fetch.
   */
  orderBy?: Prisma.QuizResponseOrderByWithRelationInput | Prisma.QuizResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuizResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuizResponses
  **/
  _count?: true | QuizResponseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: QuizResponseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: QuizResponseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuizResponseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuizResponseMaxAggregateInputType
}

export type GetQuizResponseAggregateType<T extends QuizResponseAggregateArgs> = {
      [P in keyof T & keyof AggregateQuizResponse]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuizResponse[P]>
    : Prisma.GetScalarType<T[P], AggregateQuizResponse[P]>
}




export type QuizResponseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuizResponseWhereInput
  orderBy?: Prisma.QuizResponseOrderByWithAggregationInput | Prisma.QuizResponseOrderByWithAggregationInput[]
  by: Prisma.QuizResponseScalarFieldEnum[] | Prisma.QuizResponseScalarFieldEnum
  having?: Prisma.QuizResponseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuizResponseCountAggregateInputType | true
  _avg?: QuizResponseAvgAggregateInputType
  _sum?: QuizResponseSumAggregateInputType
  _min?: QuizResponseMinAggregateInputType
  _max?: QuizResponseMaxAggregateInputType
}

export type QuizResponseGroupByOutputType = {
  id: string
  sessionId: string
  questionId: string
  textAnswer: string | null
  isCorrect: boolean | null
  score: number | null
  feedback: string | null
  answeredAt: Date
  _count: QuizResponseCountAggregateOutputType | null
  _avg: QuizResponseAvgAggregateOutputType | null
  _sum: QuizResponseSumAggregateOutputType | null
  _min: QuizResponseMinAggregateOutputType | null
  _max: QuizResponseMaxAggregateOutputType | null
}

export type GetQuizResponseGroupByPayload<T extends QuizResponseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuizResponseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuizResponseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuizResponseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuizResponseGroupByOutputType[P]>
      }
    >
  >



export type QuizResponseWhereInput = {
  AND?: Prisma.QuizResponseWhereInput | Prisma.QuizResponseWhereInput[]
  OR?: Prisma.QuizResponseWhereInput[]
  NOT?: Prisma.QuizResponseWhereInput | Prisma.QuizResponseWhereInput[]
  id?: Prisma.StringFilter<"QuizResponse"> | string
  sessionId?: Prisma.StringFilter<"QuizResponse"> | string
  questionId?: Prisma.StringFilter<"QuizResponse"> | string
  textAnswer?: Prisma.StringNullableFilter<"QuizResponse"> | string | null
  isCorrect?: Prisma.BoolNullableFilter<"QuizResponse"> | boolean | null
  score?: Prisma.FloatNullableFilter<"QuizResponse"> | number | null
  feedback?: Prisma.StringNullableFilter<"QuizResponse"> | string | null
  answeredAt?: Prisma.DateTimeFilter<"QuizResponse"> | Date | string
  session?: Prisma.XOR<Prisma.QuizSessionScalarRelationFilter, Prisma.QuizSessionWhereInput>
  question?: Prisma.XOR<Prisma.QuestionScalarRelationFilter, Prisma.QuestionWhereInput>
  answers?: Prisma.QuizResponseAnswerListRelationFilter
}

export type QuizResponseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  textAnswer?: Prisma.SortOrderInput | Prisma.SortOrder
  isCorrect?: Prisma.SortOrderInput | Prisma.SortOrder
  score?: Prisma.SortOrderInput | Prisma.SortOrder
  feedback?: Prisma.SortOrderInput | Prisma.SortOrder
  answeredAt?: Prisma.SortOrder
  session?: Prisma.QuizSessionOrderByWithRelationInput
  question?: Prisma.QuestionOrderByWithRelationInput
  answers?: Prisma.QuizResponseAnswerOrderByRelationAggregateInput
}

export type QuizResponseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  sessionId_questionId?: Prisma.QuizResponseSessionIdQuestionIdCompoundUniqueInput
  AND?: Prisma.QuizResponseWhereInput | Prisma.QuizResponseWhereInput[]
  OR?: Prisma.QuizResponseWhereInput[]
  NOT?: Prisma.QuizResponseWhereInput | Prisma.QuizResponseWhereInput[]
  sessionId?: Prisma.StringFilter<"QuizResponse"> | string
  questionId?: Prisma.StringFilter<"QuizResponse"> | string
  textAnswer?: Prisma.StringNullableFilter<"QuizResponse"> | string | null
  isCorrect?: Prisma.BoolNullableFilter<"QuizResponse"> | boolean | null
  score?: Prisma.FloatNullableFilter<"QuizResponse"> | number | null
  feedback?: Prisma.StringNullableFilter<"QuizResponse"> | string | null
  answeredAt?: Prisma.DateTimeFilter<"QuizResponse"> | Date | string
  session?: Prisma.XOR<Prisma.QuizSessionScalarRelationFilter, Prisma.QuizSessionWhereInput>
  question?: Prisma.XOR<Prisma.QuestionScalarRelationFilter, Prisma.QuestionWhereInput>
  answers?: Prisma.QuizResponseAnswerListRelationFilter
}, "id" | "sessionId_questionId">

export type QuizResponseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  textAnswer?: Prisma.SortOrderInput | Prisma.SortOrder
  isCorrect?: Prisma.SortOrderInput | Prisma.SortOrder
  score?: Prisma.SortOrderInput | Prisma.SortOrder
  feedback?: Prisma.SortOrderInput | Prisma.SortOrder
  answeredAt?: Prisma.SortOrder
  _count?: Prisma.QuizResponseCountOrderByAggregateInput
  _avg?: Prisma.QuizResponseAvgOrderByAggregateInput
  _max?: Prisma.QuizResponseMaxOrderByAggregateInput
  _min?: Prisma.QuizResponseMinOrderByAggregateInput
  _sum?: Prisma.QuizResponseSumOrderByAggregateInput
}

export type QuizResponseScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuizResponseScalarWhereWithAggregatesInput | Prisma.QuizResponseScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuizResponseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuizResponseScalarWhereWithAggregatesInput | Prisma.QuizResponseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"QuizResponse"> | string
  sessionId?: Prisma.StringWithAggregatesFilter<"QuizResponse"> | string
  questionId?: Prisma.StringWithAggregatesFilter<"QuizResponse"> | string
  textAnswer?: Prisma.StringNullableWithAggregatesFilter<"QuizResponse"> | string | null
  isCorrect?: Prisma.BoolNullableWithAggregatesFilter<"QuizResponse"> | boolean | null
  score?: Prisma.FloatNullableWithAggregatesFilter<"QuizResponse"> | number | null
  feedback?: Prisma.StringNullableWithAggregatesFilter<"QuizResponse"> | string | null
  answeredAt?: Prisma.DateTimeWithAggregatesFilter<"QuizResponse"> | Date | string
}

export type QuizResponseCreateInput = {
  id?: string
  textAnswer?: string | null
  isCorrect?: boolean | null
  score?: number | null
  feedback?: string | null
  answeredAt?: Date | string
  session: Prisma.QuizSessionCreateNestedOneWithoutResponsesInput
  question: Prisma.QuestionCreateNestedOneWithoutResponsesInput
  answers?: Prisma.QuizResponseAnswerCreateNestedManyWithoutResponseInput
}

export type QuizResponseUncheckedCreateInput = {
  id?: string
  sessionId: string
  questionId: string
  textAnswer?: string | null
  isCorrect?: boolean | null
  score?: number | null
  feedback?: string | null
  answeredAt?: Date | string
  answers?: Prisma.QuizResponseAnswerUncheckedCreateNestedManyWithoutResponseInput
}

export type QuizResponseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  textAnswer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answeredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  session?: Prisma.QuizSessionUpdateOneRequiredWithoutResponsesNestedInput
  question?: Prisma.QuestionUpdateOneRequiredWithoutResponsesNestedInput
  answers?: Prisma.QuizResponseAnswerUpdateManyWithoutResponseNestedInput
}

export type QuizResponseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  textAnswer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answeredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  answers?: Prisma.QuizResponseAnswerUncheckedUpdateManyWithoutResponseNestedInput
}

export type QuizResponseCreateManyInput = {
  id?: string
  sessionId: string
  questionId: string
  textAnswer?: string | null
  isCorrect?: boolean | null
  score?: number | null
  feedback?: string | null
  answeredAt?: Date | string
}

export type QuizResponseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  textAnswer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answeredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizResponseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  textAnswer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answeredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizResponseListRelationFilter = {
  every?: Prisma.QuizResponseWhereInput
  some?: Prisma.QuizResponseWhereInput
  none?: Prisma.QuizResponseWhereInput
}

export type QuizResponseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuizResponseSessionIdQuestionIdCompoundUniqueInput = {
  sessionId: string
  questionId: string
}

export type QuizResponseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  textAnswer?: Prisma.SortOrder
  isCorrect?: Prisma.SortOrder
  score?: Prisma.SortOrder
  feedback?: Prisma.SortOrder
  answeredAt?: Prisma.SortOrder
}

export type QuizResponseAvgOrderByAggregateInput = {
  score?: Prisma.SortOrder
}

export type QuizResponseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  textAnswer?: Prisma.SortOrder
  isCorrect?: Prisma.SortOrder
  score?: Prisma.SortOrder
  feedback?: Prisma.SortOrder
  answeredAt?: Prisma.SortOrder
}

export type QuizResponseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  textAnswer?: Prisma.SortOrder
  isCorrect?: Prisma.SortOrder
  score?: Prisma.SortOrder
  feedback?: Prisma.SortOrder
  answeredAt?: Prisma.SortOrder
}

export type QuizResponseSumOrderByAggregateInput = {
  score?: Prisma.SortOrder
}

export type QuizResponseScalarRelationFilter = {
  is?: Prisma.QuizResponseWhereInput
  isNot?: Prisma.QuizResponseWhereInput
}

export type QuizResponseCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.QuizResponseCreateWithoutQuestionInput, Prisma.QuizResponseUncheckedCreateWithoutQuestionInput> | Prisma.QuizResponseCreateWithoutQuestionInput[] | Prisma.QuizResponseUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuizResponseCreateOrConnectWithoutQuestionInput | Prisma.QuizResponseCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.QuizResponseCreateManyQuestionInputEnvelope
  connect?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
}

export type QuizResponseUncheckedCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.QuizResponseCreateWithoutQuestionInput, Prisma.QuizResponseUncheckedCreateWithoutQuestionInput> | Prisma.QuizResponseCreateWithoutQuestionInput[] | Prisma.QuizResponseUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuizResponseCreateOrConnectWithoutQuestionInput | Prisma.QuizResponseCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.QuizResponseCreateManyQuestionInputEnvelope
  connect?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
}

export type QuizResponseUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.QuizResponseCreateWithoutQuestionInput, Prisma.QuizResponseUncheckedCreateWithoutQuestionInput> | Prisma.QuizResponseCreateWithoutQuestionInput[] | Prisma.QuizResponseUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuizResponseCreateOrConnectWithoutQuestionInput | Prisma.QuizResponseCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.QuizResponseUpsertWithWhereUniqueWithoutQuestionInput | Prisma.QuizResponseUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.QuizResponseCreateManyQuestionInputEnvelope
  set?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  disconnect?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  delete?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  connect?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  update?: Prisma.QuizResponseUpdateWithWhereUniqueWithoutQuestionInput | Prisma.QuizResponseUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.QuizResponseUpdateManyWithWhereWithoutQuestionInput | Prisma.QuizResponseUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.QuizResponseScalarWhereInput | Prisma.QuizResponseScalarWhereInput[]
}

export type QuizResponseUncheckedUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.QuizResponseCreateWithoutQuestionInput, Prisma.QuizResponseUncheckedCreateWithoutQuestionInput> | Prisma.QuizResponseCreateWithoutQuestionInput[] | Prisma.QuizResponseUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuizResponseCreateOrConnectWithoutQuestionInput | Prisma.QuizResponseCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.QuizResponseUpsertWithWhereUniqueWithoutQuestionInput | Prisma.QuizResponseUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.QuizResponseCreateManyQuestionInputEnvelope
  set?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  disconnect?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  delete?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  connect?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  update?: Prisma.QuizResponseUpdateWithWhereUniqueWithoutQuestionInput | Prisma.QuizResponseUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.QuizResponseUpdateManyWithWhereWithoutQuestionInput | Prisma.QuizResponseUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.QuizResponseScalarWhereInput | Prisma.QuizResponseScalarWhereInput[]
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type QuizResponseCreateNestedOneWithoutAnswersInput = {
  create?: Prisma.XOR<Prisma.QuizResponseCreateWithoutAnswersInput, Prisma.QuizResponseUncheckedCreateWithoutAnswersInput>
  connectOrCreate?: Prisma.QuizResponseCreateOrConnectWithoutAnswersInput
  connect?: Prisma.QuizResponseWhereUniqueInput
}

export type QuizResponseUpdateOneRequiredWithoutAnswersNestedInput = {
  create?: Prisma.XOR<Prisma.QuizResponseCreateWithoutAnswersInput, Prisma.QuizResponseUncheckedCreateWithoutAnswersInput>
  connectOrCreate?: Prisma.QuizResponseCreateOrConnectWithoutAnswersInput
  upsert?: Prisma.QuizResponseUpsertWithoutAnswersInput
  connect?: Prisma.QuizResponseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.QuizResponseUpdateToOneWithWhereWithoutAnswersInput, Prisma.QuizResponseUpdateWithoutAnswersInput>, Prisma.QuizResponseUncheckedUpdateWithoutAnswersInput>
}

export type QuizResponseCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.QuizResponseCreateWithoutSessionInput, Prisma.QuizResponseUncheckedCreateWithoutSessionInput> | Prisma.QuizResponseCreateWithoutSessionInput[] | Prisma.QuizResponseUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.QuizResponseCreateOrConnectWithoutSessionInput | Prisma.QuizResponseCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.QuizResponseCreateManySessionInputEnvelope
  connect?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
}

export type QuizResponseUncheckedCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.QuizResponseCreateWithoutSessionInput, Prisma.QuizResponseUncheckedCreateWithoutSessionInput> | Prisma.QuizResponseCreateWithoutSessionInput[] | Prisma.QuizResponseUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.QuizResponseCreateOrConnectWithoutSessionInput | Prisma.QuizResponseCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.QuizResponseCreateManySessionInputEnvelope
  connect?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
}

export type QuizResponseUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.QuizResponseCreateWithoutSessionInput, Prisma.QuizResponseUncheckedCreateWithoutSessionInput> | Prisma.QuizResponseCreateWithoutSessionInput[] | Prisma.QuizResponseUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.QuizResponseCreateOrConnectWithoutSessionInput | Prisma.QuizResponseCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.QuizResponseUpsertWithWhereUniqueWithoutSessionInput | Prisma.QuizResponseUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.QuizResponseCreateManySessionInputEnvelope
  set?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  disconnect?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  delete?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  connect?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  update?: Prisma.QuizResponseUpdateWithWhereUniqueWithoutSessionInput | Prisma.QuizResponseUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.QuizResponseUpdateManyWithWhereWithoutSessionInput | Prisma.QuizResponseUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.QuizResponseScalarWhereInput | Prisma.QuizResponseScalarWhereInput[]
}

export type QuizResponseUncheckedUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.QuizResponseCreateWithoutSessionInput, Prisma.QuizResponseUncheckedCreateWithoutSessionInput> | Prisma.QuizResponseCreateWithoutSessionInput[] | Prisma.QuizResponseUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.QuizResponseCreateOrConnectWithoutSessionInput | Prisma.QuizResponseCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.QuizResponseUpsertWithWhereUniqueWithoutSessionInput | Prisma.QuizResponseUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.QuizResponseCreateManySessionInputEnvelope
  set?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  disconnect?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  delete?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  connect?: Prisma.QuizResponseWhereUniqueInput | Prisma.QuizResponseWhereUniqueInput[]
  update?: Prisma.QuizResponseUpdateWithWhereUniqueWithoutSessionInput | Prisma.QuizResponseUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.QuizResponseUpdateManyWithWhereWithoutSessionInput | Prisma.QuizResponseUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.QuizResponseScalarWhereInput | Prisma.QuizResponseScalarWhereInput[]
}

export type QuizResponseCreateWithoutQuestionInput = {
  id?: string
  textAnswer?: string | null
  isCorrect?: boolean | null
  score?: number | null
  feedback?: string | null
  answeredAt?: Date | string
  session: Prisma.QuizSessionCreateNestedOneWithoutResponsesInput
  answers?: Prisma.QuizResponseAnswerCreateNestedManyWithoutResponseInput
}

export type QuizResponseUncheckedCreateWithoutQuestionInput = {
  id?: string
  sessionId: string
  textAnswer?: string | null
  isCorrect?: boolean | null
  score?: number | null
  feedback?: string | null
  answeredAt?: Date | string
  answers?: Prisma.QuizResponseAnswerUncheckedCreateNestedManyWithoutResponseInput
}

export type QuizResponseCreateOrConnectWithoutQuestionInput = {
  where: Prisma.QuizResponseWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizResponseCreateWithoutQuestionInput, Prisma.QuizResponseUncheckedCreateWithoutQuestionInput>
}

export type QuizResponseCreateManyQuestionInputEnvelope = {
  data: Prisma.QuizResponseCreateManyQuestionInput | Prisma.QuizResponseCreateManyQuestionInput[]
  skipDuplicates?: boolean
}

export type QuizResponseUpsertWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.QuizResponseWhereUniqueInput
  update: Prisma.XOR<Prisma.QuizResponseUpdateWithoutQuestionInput, Prisma.QuizResponseUncheckedUpdateWithoutQuestionInput>
  create: Prisma.XOR<Prisma.QuizResponseCreateWithoutQuestionInput, Prisma.QuizResponseUncheckedCreateWithoutQuestionInput>
}

export type QuizResponseUpdateWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.QuizResponseWhereUniqueInput
  data: Prisma.XOR<Prisma.QuizResponseUpdateWithoutQuestionInput, Prisma.QuizResponseUncheckedUpdateWithoutQuestionInput>
}

export type QuizResponseUpdateManyWithWhereWithoutQuestionInput = {
  where: Prisma.QuizResponseScalarWhereInput
  data: Prisma.XOR<Prisma.QuizResponseUpdateManyMutationInput, Prisma.QuizResponseUncheckedUpdateManyWithoutQuestionInput>
}

export type QuizResponseScalarWhereInput = {
  AND?: Prisma.QuizResponseScalarWhereInput | Prisma.QuizResponseScalarWhereInput[]
  OR?: Prisma.QuizResponseScalarWhereInput[]
  NOT?: Prisma.QuizResponseScalarWhereInput | Prisma.QuizResponseScalarWhereInput[]
  id?: Prisma.StringFilter<"QuizResponse"> | string
  sessionId?: Prisma.StringFilter<"QuizResponse"> | string
  questionId?: Prisma.StringFilter<"QuizResponse"> | string
  textAnswer?: Prisma.StringNullableFilter<"QuizResponse"> | string | null
  isCorrect?: Prisma.BoolNullableFilter<"QuizResponse"> | boolean | null
  score?: Prisma.FloatNullableFilter<"QuizResponse"> | number | null
  feedback?: Prisma.StringNullableFilter<"QuizResponse"> | string | null
  answeredAt?: Prisma.DateTimeFilter<"QuizResponse"> | Date | string
}

export type QuizResponseCreateWithoutAnswersInput = {
  id?: string
  textAnswer?: string | null
  isCorrect?: boolean | null
  score?: number | null
  feedback?: string | null
  answeredAt?: Date | string
  session: Prisma.QuizSessionCreateNestedOneWithoutResponsesInput
  question: Prisma.QuestionCreateNestedOneWithoutResponsesInput
}

export type QuizResponseUncheckedCreateWithoutAnswersInput = {
  id?: string
  sessionId: string
  questionId: string
  textAnswer?: string | null
  isCorrect?: boolean | null
  score?: number | null
  feedback?: string | null
  answeredAt?: Date | string
}

export type QuizResponseCreateOrConnectWithoutAnswersInput = {
  where: Prisma.QuizResponseWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizResponseCreateWithoutAnswersInput, Prisma.QuizResponseUncheckedCreateWithoutAnswersInput>
}

export type QuizResponseUpsertWithoutAnswersInput = {
  update: Prisma.XOR<Prisma.QuizResponseUpdateWithoutAnswersInput, Prisma.QuizResponseUncheckedUpdateWithoutAnswersInput>
  create: Prisma.XOR<Prisma.QuizResponseCreateWithoutAnswersInput, Prisma.QuizResponseUncheckedCreateWithoutAnswersInput>
  where?: Prisma.QuizResponseWhereInput
}

export type QuizResponseUpdateToOneWithWhereWithoutAnswersInput = {
  where?: Prisma.QuizResponseWhereInput
  data: Prisma.XOR<Prisma.QuizResponseUpdateWithoutAnswersInput, Prisma.QuizResponseUncheckedUpdateWithoutAnswersInput>
}

export type QuizResponseUpdateWithoutAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  textAnswer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answeredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  session?: Prisma.QuizSessionUpdateOneRequiredWithoutResponsesNestedInput
  question?: Prisma.QuestionUpdateOneRequiredWithoutResponsesNestedInput
}

export type QuizResponseUncheckedUpdateWithoutAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  textAnswer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answeredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizResponseCreateWithoutSessionInput = {
  id?: string
  textAnswer?: string | null
  isCorrect?: boolean | null
  score?: number | null
  feedback?: string | null
  answeredAt?: Date | string
  question: Prisma.QuestionCreateNestedOneWithoutResponsesInput
  answers?: Prisma.QuizResponseAnswerCreateNestedManyWithoutResponseInput
}

export type QuizResponseUncheckedCreateWithoutSessionInput = {
  id?: string
  questionId: string
  textAnswer?: string | null
  isCorrect?: boolean | null
  score?: number | null
  feedback?: string | null
  answeredAt?: Date | string
  answers?: Prisma.QuizResponseAnswerUncheckedCreateNestedManyWithoutResponseInput
}

export type QuizResponseCreateOrConnectWithoutSessionInput = {
  where: Prisma.QuizResponseWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizResponseCreateWithoutSessionInput, Prisma.QuizResponseUncheckedCreateWithoutSessionInput>
}

export type QuizResponseCreateManySessionInputEnvelope = {
  data: Prisma.QuizResponseCreateManySessionInput | Prisma.QuizResponseCreateManySessionInput[]
  skipDuplicates?: boolean
}

export type QuizResponseUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.QuizResponseWhereUniqueInput
  update: Prisma.XOR<Prisma.QuizResponseUpdateWithoutSessionInput, Prisma.QuizResponseUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.QuizResponseCreateWithoutSessionInput, Prisma.QuizResponseUncheckedCreateWithoutSessionInput>
}

export type QuizResponseUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.QuizResponseWhereUniqueInput
  data: Prisma.XOR<Prisma.QuizResponseUpdateWithoutSessionInput, Prisma.QuizResponseUncheckedUpdateWithoutSessionInput>
}

export type QuizResponseUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.QuizResponseScalarWhereInput
  data: Prisma.XOR<Prisma.QuizResponseUpdateManyMutationInput, Prisma.QuizResponseUncheckedUpdateManyWithoutSessionInput>
}

export type QuizResponseCreateManyQuestionInput = {
  id?: string
  sessionId: string
  textAnswer?: string | null
  isCorrect?: boolean | null
  score?: number | null
  feedback?: string | null
  answeredAt?: Date | string
}

export type QuizResponseUpdateWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  textAnswer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answeredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  session?: Prisma.QuizSessionUpdateOneRequiredWithoutResponsesNestedInput
  answers?: Prisma.QuizResponseAnswerUpdateManyWithoutResponseNestedInput
}

export type QuizResponseUncheckedUpdateWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  textAnswer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answeredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  answers?: Prisma.QuizResponseAnswerUncheckedUpdateManyWithoutResponseNestedInput
}

export type QuizResponseUncheckedUpdateManyWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  textAnswer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answeredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizResponseCreateManySessionInput = {
  id?: string
  questionId: string
  textAnswer?: string | null
  isCorrect?: boolean | null
  score?: number | null
  feedback?: string | null
  answeredAt?: Date | string
}

export type QuizResponseUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  textAnswer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answeredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  question?: Prisma.QuestionUpdateOneRequiredWithoutResponsesNestedInput
  answers?: Prisma.QuizResponseAnswerUpdateManyWithoutResponseNestedInput
}

export type QuizResponseUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  textAnswer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answeredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  answers?: Prisma.QuizResponseAnswerUncheckedUpdateManyWithoutResponseNestedInput
}

export type QuizResponseUncheckedUpdateManyWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  textAnswer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCorrect?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  feedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answeredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type QuizResponseCountOutputType
 */

export type QuizResponseCountOutputType = {
  answers: number
}

export type QuizResponseCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  answers?: boolean | QuizResponseCountOutputTypeCountAnswersArgs
}

/**
 * QuizResponseCountOutputType without action
 */
export type QuizResponseCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseCountOutputType
   */
  select?: Prisma.QuizResponseCountOutputTypeSelect<ExtArgs> | null
}

/**
 * QuizResponseCountOutputType without action
 */
export type QuizResponseCountOutputTypeCountAnswersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuizResponseAnswerWhereInput
}


export type QuizResponseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  questionId?: boolean
  textAnswer?: boolean
  isCorrect?: boolean
  score?: boolean
  feedback?: boolean
  answeredAt?: boolean
  session?: boolean | Prisma.QuizSessionDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  answers?: boolean | Prisma.QuizResponse$answersArgs<ExtArgs>
  _count?: boolean | Prisma.QuizResponseCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizResponse"]>

export type QuizResponseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  questionId?: boolean
  textAnswer?: boolean
  isCorrect?: boolean
  score?: boolean
  feedback?: boolean
  answeredAt?: boolean
  session?: boolean | Prisma.QuizSessionDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizResponse"]>

export type QuizResponseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  questionId?: boolean
  textAnswer?: boolean
  isCorrect?: boolean
  score?: boolean
  feedback?: boolean
  answeredAt?: boolean
  session?: boolean | Prisma.QuizSessionDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizResponse"]>

export type QuizResponseSelectScalar = {
  id?: boolean
  sessionId?: boolean
  questionId?: boolean
  textAnswer?: boolean
  isCorrect?: boolean
  score?: boolean
  feedback?: boolean
  answeredAt?: boolean
}

export type QuizResponseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sessionId" | "questionId" | "textAnswer" | "isCorrect" | "score" | "feedback" | "answeredAt", ExtArgs["result"]["quizResponse"]>
export type QuizResponseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.QuizSessionDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  answers?: boolean | Prisma.QuizResponse$answersArgs<ExtArgs>
  _count?: boolean | Prisma.QuizResponseCountOutputTypeDefaultArgs<ExtArgs>
}
export type QuizResponseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.QuizSessionDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}
export type QuizResponseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.QuizSessionDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}

export type $QuizResponsePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuizResponse"
  objects: {
    session: Prisma.$QuizSessionPayload<ExtArgs>
    question: Prisma.$QuestionPayload<ExtArgs>
    answers: Prisma.$QuizResponseAnswerPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    sessionId: string
    questionId: string
    textAnswer: string | null
    isCorrect: boolean | null
    score: number | null
    feedback: string | null
    answeredAt: Date
  }, ExtArgs["result"]["quizResponse"]>
  composites: {}
}

export type QuizResponseGetPayload<S extends boolean | null | undefined | QuizResponseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload, S>

export type QuizResponseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuizResponseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuizResponseCountAggregateInputType | true
  }

export interface QuizResponseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuizResponse'], meta: { name: 'QuizResponse' } }
  /**
   * Find zero or one QuizResponse that matches the filter.
   * @param {QuizResponseFindUniqueArgs} args - Arguments to find a QuizResponse
   * @example
   * // Get one QuizResponse
   * const quizResponse = await prisma.quizResponse.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuizResponseFindUniqueArgs>(args: Prisma.SelectSubset<T, QuizResponseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuizResponseClient<runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuizResponse that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuizResponseFindUniqueOrThrowArgs} args - Arguments to find a QuizResponse
   * @example
   * // Get one QuizResponse
   * const quizResponse = await prisma.quizResponse.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuizResponseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuizResponseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizResponseClient<runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizResponse that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseFindFirstArgs} args - Arguments to find a QuizResponse
   * @example
   * // Get one QuizResponse
   * const quizResponse = await prisma.quizResponse.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuizResponseFindFirstArgs>(args?: Prisma.SelectSubset<T, QuizResponseFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuizResponseClient<runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizResponse that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseFindFirstOrThrowArgs} args - Arguments to find a QuizResponse
   * @example
   * // Get one QuizResponse
   * const quizResponse = await prisma.quizResponse.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuizResponseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuizResponseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizResponseClient<runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuizResponses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuizResponses
   * const quizResponses = await prisma.quizResponse.findMany()
   * 
   * // Get first 10 QuizResponses
   * const quizResponses = await prisma.quizResponse.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const quizResponseWithIdOnly = await prisma.quizResponse.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuizResponseFindManyArgs>(args?: Prisma.SelectSubset<T, QuizResponseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuizResponse.
   * @param {QuizResponseCreateArgs} args - Arguments to create a QuizResponse.
   * @example
   * // Create one QuizResponse
   * const QuizResponse = await prisma.quizResponse.create({
   *   data: {
   *     // ... data to create a QuizResponse
   *   }
   * })
   * 
   */
  create<T extends QuizResponseCreateArgs>(args: Prisma.SelectSubset<T, QuizResponseCreateArgs<ExtArgs>>): Prisma.Prisma__QuizResponseClient<runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuizResponses.
   * @param {QuizResponseCreateManyArgs} args - Arguments to create many QuizResponses.
   * @example
   * // Create many QuizResponses
   * const quizResponse = await prisma.quizResponse.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuizResponseCreateManyArgs>(args?: Prisma.SelectSubset<T, QuizResponseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuizResponses and returns the data saved in the database.
   * @param {QuizResponseCreateManyAndReturnArgs} args - Arguments to create many QuizResponses.
   * @example
   * // Create many QuizResponses
   * const quizResponse = await prisma.quizResponse.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuizResponses and only return the `id`
   * const quizResponseWithIdOnly = await prisma.quizResponse.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuizResponseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuizResponseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuizResponse.
   * @param {QuizResponseDeleteArgs} args - Arguments to delete one QuizResponse.
   * @example
   * // Delete one QuizResponse
   * const QuizResponse = await prisma.quizResponse.delete({
   *   where: {
   *     // ... filter to delete one QuizResponse
   *   }
   * })
   * 
   */
  delete<T extends QuizResponseDeleteArgs>(args: Prisma.SelectSubset<T, QuizResponseDeleteArgs<ExtArgs>>): Prisma.Prisma__QuizResponseClient<runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuizResponse.
   * @param {QuizResponseUpdateArgs} args - Arguments to update one QuizResponse.
   * @example
   * // Update one QuizResponse
   * const quizResponse = await prisma.quizResponse.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuizResponseUpdateArgs>(args: Prisma.SelectSubset<T, QuizResponseUpdateArgs<ExtArgs>>): Prisma.Prisma__QuizResponseClient<runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuizResponses.
   * @param {QuizResponseDeleteManyArgs} args - Arguments to filter QuizResponses to delete.
   * @example
   * // Delete a few QuizResponses
   * const { count } = await prisma.quizResponse.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuizResponseDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuizResponseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizResponses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuizResponses
   * const quizResponse = await prisma.quizResponse.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuizResponseUpdateManyArgs>(args: Prisma.SelectSubset<T, QuizResponseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizResponses and returns the data updated in the database.
   * @param {QuizResponseUpdateManyAndReturnArgs} args - Arguments to update many QuizResponses.
   * @example
   * // Update many QuizResponses
   * const quizResponse = await prisma.quizResponse.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuizResponses and only return the `id`
   * const quizResponseWithIdOnly = await prisma.quizResponse.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuizResponseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuizResponseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuizResponse.
   * @param {QuizResponseUpsertArgs} args - Arguments to update or create a QuizResponse.
   * @example
   * // Update or create a QuizResponse
   * const quizResponse = await prisma.quizResponse.upsert({
   *   create: {
   *     // ... data to create a QuizResponse
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuizResponse we want to update
   *   }
   * })
   */
  upsert<T extends QuizResponseUpsertArgs>(args: Prisma.SelectSubset<T, QuizResponseUpsertArgs<ExtArgs>>): Prisma.Prisma__QuizResponseClient<runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuizResponses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseCountArgs} args - Arguments to filter QuizResponses to count.
   * @example
   * // Count the number of QuizResponses
   * const count = await prisma.quizResponse.count({
   *   where: {
   *     // ... the filter for the QuizResponses we want to count
   *   }
   * })
  **/
  count<T extends QuizResponseCountArgs>(
    args?: Prisma.Subset<T, QuizResponseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuizResponseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuizResponse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuizResponseAggregateArgs>(args: Prisma.Subset<T, QuizResponseAggregateArgs>): Prisma.PrismaPromise<GetQuizResponseAggregateType<T>>

  /**
   * Group by QuizResponse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuizResponseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuizResponseGroupByArgs['orderBy'] }
      : { orderBy?: QuizResponseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuizResponseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuizResponseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuizResponse model
 */
readonly fields: QuizResponseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuizResponse.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuizResponseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  session<T extends Prisma.QuizSessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuizSessionDefaultArgs<ExtArgs>>): Prisma.Prisma__QuizSessionClient<runtime.Types.Result.GetResult<Prisma.$QuizSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  question<T extends Prisma.QuestionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuestionDefaultArgs<ExtArgs>>): Prisma.Prisma__QuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  answers<T extends Prisma.QuizResponse$answersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuizResponse$answersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizResponseAnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuizResponse model
 */
export interface QuizResponseFieldRefs {
  readonly id: Prisma.FieldRef<"QuizResponse", 'String'>
  readonly sessionId: Prisma.FieldRef<"QuizResponse", 'String'>
  readonly questionId: Prisma.FieldRef<"QuizResponse", 'String'>
  readonly textAnswer: Prisma.FieldRef<"QuizResponse", 'String'>
  readonly isCorrect: Prisma.FieldRef<"QuizResponse", 'Boolean'>
  readonly score: Prisma.FieldRef<"QuizResponse", 'Float'>
  readonly feedback: Prisma.FieldRef<"QuizResponse", 'String'>
  readonly answeredAt: Prisma.FieldRef<"QuizResponse", 'DateTime'>
}
    

// Custom InputTypes
/**
 * QuizResponse findUnique
 */
export type QuizResponseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponse
   */
  select?: Prisma.QuizResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponse
   */
  omit?: Prisma.QuizResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseInclude<ExtArgs> | null
  /**
   * Filter, which QuizResponse to fetch.
   */
  where: Prisma.QuizResponseWhereUniqueInput
}

/**
 * QuizResponse findUniqueOrThrow
 */
export type QuizResponseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponse
   */
  select?: Prisma.QuizResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponse
   */
  omit?: Prisma.QuizResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseInclude<ExtArgs> | null
  /**
   * Filter, which QuizResponse to fetch.
   */
  where: Prisma.QuizResponseWhereUniqueInput
}

/**
 * QuizResponse findFirst
 */
export type QuizResponseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponse
   */
  select?: Prisma.QuizResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponse
   */
  omit?: Prisma.QuizResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseInclude<ExtArgs> | null
  /**
   * Filter, which QuizResponse to fetch.
   */
  where?: Prisma.QuizResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizResponses to fetch.
   */
  orderBy?: Prisma.QuizResponseOrderByWithRelationInput | Prisma.QuizResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizResponses.
   */
  cursor?: Prisma.QuizResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizResponses.
   */
  distinct?: Prisma.QuizResponseScalarFieldEnum | Prisma.QuizResponseScalarFieldEnum[]
}

/**
 * QuizResponse findFirstOrThrow
 */
export type QuizResponseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponse
   */
  select?: Prisma.QuizResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponse
   */
  omit?: Prisma.QuizResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseInclude<ExtArgs> | null
  /**
   * Filter, which QuizResponse to fetch.
   */
  where?: Prisma.QuizResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizResponses to fetch.
   */
  orderBy?: Prisma.QuizResponseOrderByWithRelationInput | Prisma.QuizResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizResponses.
   */
  cursor?: Prisma.QuizResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizResponses.
   */
  distinct?: Prisma.QuizResponseScalarFieldEnum | Prisma.QuizResponseScalarFieldEnum[]
}

/**
 * QuizResponse findMany
 */
export type QuizResponseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponse
   */
  select?: Prisma.QuizResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponse
   */
  omit?: Prisma.QuizResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseInclude<ExtArgs> | null
  /**
   * Filter, which QuizResponses to fetch.
   */
  where?: Prisma.QuizResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizResponses to fetch.
   */
  orderBy?: Prisma.QuizResponseOrderByWithRelationInput | Prisma.QuizResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuizResponses.
   */
  cursor?: Prisma.QuizResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizResponses.
   */
  distinct?: Prisma.QuizResponseScalarFieldEnum | Prisma.QuizResponseScalarFieldEnum[]
}

/**
 * QuizResponse create
 */
export type QuizResponseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponse
   */
  select?: Prisma.QuizResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponse
   */
  omit?: Prisma.QuizResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseInclude<ExtArgs> | null
  /**
   * The data needed to create a QuizResponse.
   */
  data: Prisma.XOR<Prisma.QuizResponseCreateInput, Prisma.QuizResponseUncheckedCreateInput>
}

/**
 * QuizResponse createMany
 */
export type QuizResponseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuizResponses.
   */
  data: Prisma.QuizResponseCreateManyInput | Prisma.QuizResponseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QuizResponse createManyAndReturn
 */
export type QuizResponseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponse
   */
  select?: Prisma.QuizResponseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponse
   */
  omit?: Prisma.QuizResponseOmit<ExtArgs> | null
  /**
   * The data used to create many QuizResponses.
   */
  data: Prisma.QuizResponseCreateManyInput | Prisma.QuizResponseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuizResponse update
 */
export type QuizResponseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponse
   */
  select?: Prisma.QuizResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponse
   */
  omit?: Prisma.QuizResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseInclude<ExtArgs> | null
  /**
   * The data needed to update a QuizResponse.
   */
  data: Prisma.XOR<Prisma.QuizResponseUpdateInput, Prisma.QuizResponseUncheckedUpdateInput>
  /**
   * Choose, which QuizResponse to update.
   */
  where: Prisma.QuizResponseWhereUniqueInput
}

/**
 * QuizResponse updateMany
 */
export type QuizResponseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuizResponses.
   */
  data: Prisma.XOR<Prisma.QuizResponseUpdateManyMutationInput, Prisma.QuizResponseUncheckedUpdateManyInput>
  /**
   * Filter which QuizResponses to update
   */
  where?: Prisma.QuizResponseWhereInput
  /**
   * Limit how many QuizResponses to update.
   */
  limit?: number
}

/**
 * QuizResponse updateManyAndReturn
 */
export type QuizResponseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponse
   */
  select?: Prisma.QuizResponseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponse
   */
  omit?: Prisma.QuizResponseOmit<ExtArgs> | null
  /**
   * The data used to update QuizResponses.
   */
  data: Prisma.XOR<Prisma.QuizResponseUpdateManyMutationInput, Prisma.QuizResponseUncheckedUpdateManyInput>
  /**
   * Filter which QuizResponses to update
   */
  where?: Prisma.QuizResponseWhereInput
  /**
   * Limit how many QuizResponses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuizResponse upsert
 */
export type QuizResponseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponse
   */
  select?: Prisma.QuizResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponse
   */
  omit?: Prisma.QuizResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseInclude<ExtArgs> | null
  /**
   * The filter to search for the QuizResponse to update in case it exists.
   */
  where: Prisma.QuizResponseWhereUniqueInput
  /**
   * In case the QuizResponse found by the `where` argument doesn't exist, create a new QuizResponse with this data.
   */
  create: Prisma.XOR<Prisma.QuizResponseCreateInput, Prisma.QuizResponseUncheckedCreateInput>
  /**
   * In case the QuizResponse was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuizResponseUpdateInput, Prisma.QuizResponseUncheckedUpdateInput>
}

/**
 * QuizResponse delete
 */
export type QuizResponseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponse
   */
  select?: Prisma.QuizResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponse
   */
  omit?: Prisma.QuizResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseInclude<ExtArgs> | null
  /**
   * Filter which QuizResponse to delete.
   */
  where: Prisma.QuizResponseWhereUniqueInput
}

/**
 * QuizResponse deleteMany
 */
export type QuizResponseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizResponses to delete
   */
  where?: Prisma.QuizResponseWhereInput
  /**
   * Limit how many QuizResponses to delete.
   */
  limit?: number
}

/**
 * QuizResponse.answers
 */
export type QuizResponse$answersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseAnswer
   */
  select?: Prisma.QuizResponseAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponseAnswer
   */
  omit?: Prisma.QuizResponseAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseAnswerInclude<ExtArgs> | null
  where?: Prisma.QuizResponseAnswerWhereInput
  orderBy?: Prisma.QuizResponseAnswerOrderByWithRelationInput | Prisma.QuizResponseAnswerOrderByWithRelationInput[]
  cursor?: Prisma.QuizResponseAnswerWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.QuizResponseAnswerScalarFieldEnum | Prisma.QuizResponseAnswerScalarFieldEnum[]
}

/**
 * QuizResponse without action
 */
export type QuizResponseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponse
   */
  select?: Prisma.QuizResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponse
   */
  omit?: Prisma.QuizResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseInclude<ExtArgs> | null
}
