
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QuizResponseAnswer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model QuizResponseAnswer
 * 
 */
export type QuizResponseAnswerModel = runtime.Types.Result.DefaultSelection<Prisma.$QuizResponseAnswerPayload>

export type AggregateQuizResponseAnswer = {
  _count: QuizResponseAnswerCountAggregateOutputType | null
  _min: QuizResponseAnswerMinAggregateOutputType | null
  _max: QuizResponseAnswerMaxAggregateOutputType | null
}

export type QuizResponseAnswerMinAggregateOutputType = {
  responseId: string | null
  answerOptionId: string | null
}

export type QuizResponseAnswerMaxAggregateOutputType = {
  responseId: string | null
  answerOptionId: string | null
}

export type QuizResponseAnswerCountAggregateOutputType = {
  responseId: number
  answerOptionId: number
  _all: number
}


export type QuizResponseAnswerMinAggregateInputType = {
  responseId?: true
  answerOptionId?: true
}

export type QuizResponseAnswerMaxAggregateInputType = {
  responseId?: true
  answerOptionId?: true
}

export type QuizResponseAnswerCountAggregateInputType = {
  responseId?: true
  answerOptionId?: true
  _all?: true
}

export type QuizResponseAnswerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizResponseAnswer to aggregate.
   */
  where?: Prisma.QuizResponseAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizResponseAnswers to fetch.
   */
  orderBy?: Prisma.QuizResponseAnswerOrderByWithRelationInput | Prisma.QuizResponseAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuizResponseAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizResponseAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizResponseAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuizResponseAnswers
  **/
  _count?: true | QuizResponseAnswerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuizResponseAnswerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuizResponseAnswerMaxAggregateInputType
}

export type GetQuizResponseAnswerAggregateType<T extends QuizResponseAnswerAggregateArgs> = {
      [P in keyof T & keyof AggregateQuizResponseAnswer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuizResponseAnswer[P]>
    : Prisma.GetScalarType<T[P], AggregateQuizResponseAnswer[P]>
}




export type QuizResponseAnswerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuizResponseAnswerWhereInput
  orderBy?: Prisma.QuizResponseAnswerOrderByWithAggregationInput | Prisma.QuizResponseAnswerOrderByWithAggregationInput[]
  by: Prisma.QuizResponseAnswerScalarFieldEnum[] | Prisma.QuizResponseAnswerScalarFieldEnum
  having?: Prisma.QuizResponseAnswerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuizResponseAnswerCountAggregateInputType | true
  _min?: QuizResponseAnswerMinAggregateInputType
  _max?: QuizResponseAnswerMaxAggregateInputType
}

export type QuizResponseAnswerGroupByOutputType = {
  responseId: string
  answerOptionId: string
  _count: QuizResponseAnswerCountAggregateOutputType | null
  _min: QuizResponseAnswerMinAggregateOutputType | null
  _max: QuizResponseAnswerMaxAggregateOutputType | null
}

export type GetQuizResponseAnswerGroupByPayload<T extends QuizResponseAnswerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuizResponseAnswerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuizResponseAnswerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuizResponseAnswerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuizResponseAnswerGroupByOutputType[P]>
      }
    >
  >



export type QuizResponseAnswerWhereInput = {
  AND?: Prisma.QuizResponseAnswerWhereInput | Prisma.QuizResponseAnswerWhereInput[]
  OR?: Prisma.QuizResponseAnswerWhereInput[]
  NOT?: Prisma.QuizResponseAnswerWhereInput | Prisma.QuizResponseAnswerWhereInput[]
  responseId?: Prisma.StringFilter<"QuizResponseAnswer"> | string
  answerOptionId?: Prisma.StringFilter<"QuizResponseAnswer"> | string
  response?: Prisma.XOR<Prisma.QuizResponseScalarRelationFilter, Prisma.QuizResponseWhereInput>
  answerOption?: Prisma.XOR<Prisma.AnswerOptionScalarRelationFilter, Prisma.AnswerOptionWhereInput>
}

export type QuizResponseAnswerOrderByWithRelationInput = {
  responseId?: Prisma.SortOrder
  answerOptionId?: Prisma.SortOrder
  response?: Prisma.QuizResponseOrderByWithRelationInput
  answerOption?: Prisma.AnswerOptionOrderByWithRelationInput
}

export type QuizResponseAnswerWhereUniqueInput = Prisma.AtLeast<{
  responseId_answerOptionId?: Prisma.QuizResponseAnswerResponseIdAnswerOptionIdCompoundUniqueInput
  AND?: Prisma.QuizResponseAnswerWhereInput | Prisma.QuizResponseAnswerWhereInput[]
  OR?: Prisma.QuizResponseAnswerWhereInput[]
  NOT?: Prisma.QuizResponseAnswerWhereInput | Prisma.QuizResponseAnswerWhereInput[]
  responseId?: Prisma.StringFilter<"QuizResponseAnswer"> | string
  answerOptionId?: Prisma.StringFilter<"QuizResponseAnswer"> | string
  response?: Prisma.XOR<Prisma.QuizResponseScalarRelationFilter, Prisma.QuizResponseWhereInput>
  answerOption?: Prisma.XOR<Prisma.AnswerOptionScalarRelationFilter, Prisma.AnswerOptionWhereInput>
}, "responseId_answerOptionId">

export type QuizResponseAnswerOrderByWithAggregationInput = {
  responseId?: Prisma.SortOrder
  answerOptionId?: Prisma.SortOrder
  _count?: Prisma.QuizResponseAnswerCountOrderByAggregateInput
  _max?: Prisma.QuizResponseAnswerMaxOrderByAggregateInput
  _min?: Prisma.QuizResponseAnswerMinOrderByAggregateInput
}

export type QuizResponseAnswerScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuizResponseAnswerScalarWhereWithAggregatesInput | Prisma.QuizResponseAnswerScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuizResponseAnswerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuizResponseAnswerScalarWhereWithAggregatesInput | Prisma.QuizResponseAnswerScalarWhereWithAggregatesInput[]
  responseId?: Prisma.StringWithAggregatesFilter<"QuizResponseAnswer"> | string
  answerOptionId?: Prisma.StringWithAggregatesFilter<"QuizResponseAnswer"> | string
}

export type QuizResponseAnswerCreateInput = {
  response: Prisma.QuizResponseCreateNestedOneWithoutAnswersInput
  answerOption: Prisma.AnswerOptionCreateNestedOneWithoutResponsesInput
}

export type QuizResponseAnswerUncheckedCreateInput = {
  responseId: string
  answerOptionId: string
}

export type QuizResponseAnswerUpdateInput = {
  response?: Prisma.QuizResponseUpdateOneRequiredWithoutAnswersNestedInput
  answerOption?: Prisma.AnswerOptionUpdateOneRequiredWithoutResponsesNestedInput
}

export type QuizResponseAnswerUncheckedUpdateInput = {
  responseId?: Prisma.StringFieldUpdateOperationsInput | string
  answerOptionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type QuizResponseAnswerCreateManyInput = {
  responseId: string
  answerOptionId: string
}

export type QuizResponseAnswerUpdateManyMutationInput = {

}

export type QuizResponseAnswerUncheckedUpdateManyInput = {
  responseId?: Prisma.StringFieldUpdateOperationsInput | string
  answerOptionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type QuizResponseAnswerListRelationFilter = {
  every?: Prisma.QuizResponseAnswerWhereInput
  some?: Prisma.QuizResponseAnswerWhereInput
  none?: Prisma.QuizResponseAnswerWhereInput
}

export type QuizResponseAnswerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuizResponseAnswerResponseIdAnswerOptionIdCompoundUniqueInput = {
  responseId: string
  answerOptionId: string
}

export type QuizResponseAnswerCountOrderByAggregateInput = {
  responseId?: Prisma.SortOrder
  answerOptionId?: Prisma.SortOrder
}

export type QuizResponseAnswerMaxOrderByAggregateInput = {
  responseId?: Prisma.SortOrder
  answerOptionId?: Prisma.SortOrder
}

export type QuizResponseAnswerMinOrderByAggregateInput = {
  responseId?: Prisma.SortOrder
  answerOptionId?: Prisma.SortOrder
}

export type QuizResponseAnswerCreateNestedManyWithoutAnswerOptionInput = {
  create?: Prisma.XOR<Prisma.QuizResponseAnswerCreateWithoutAnswerOptionInput, Prisma.QuizResponseAnswerUncheckedCreateWithoutAnswerOptionInput> | Prisma.QuizResponseAnswerCreateWithoutAnswerOptionInput[] | Prisma.QuizResponseAnswerUncheckedCreateWithoutAnswerOptionInput[]
  connectOrCreate?: Prisma.QuizResponseAnswerCreateOrConnectWithoutAnswerOptionInput | Prisma.QuizResponseAnswerCreateOrConnectWithoutAnswerOptionInput[]
  createMany?: Prisma.QuizResponseAnswerCreateManyAnswerOptionInputEnvelope
  connect?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
}

export type QuizResponseAnswerUncheckedCreateNestedManyWithoutAnswerOptionInput = {
  create?: Prisma.XOR<Prisma.QuizResponseAnswerCreateWithoutAnswerOptionInput, Prisma.QuizResponseAnswerUncheckedCreateWithoutAnswerOptionInput> | Prisma.QuizResponseAnswerCreateWithoutAnswerOptionInput[] | Prisma.QuizResponseAnswerUncheckedCreateWithoutAnswerOptionInput[]
  connectOrCreate?: Prisma.QuizResponseAnswerCreateOrConnectWithoutAnswerOptionInput | Prisma.QuizResponseAnswerCreateOrConnectWithoutAnswerOptionInput[]
  createMany?: Prisma.QuizResponseAnswerCreateManyAnswerOptionInputEnvelope
  connect?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
}

export type QuizResponseAnswerUpdateManyWithoutAnswerOptionNestedInput = {
  create?: Prisma.XOR<Prisma.QuizResponseAnswerCreateWithoutAnswerOptionInput, Prisma.QuizResponseAnswerUncheckedCreateWithoutAnswerOptionInput> | Prisma.QuizResponseAnswerCreateWithoutAnswerOptionInput[] | Prisma.QuizResponseAnswerUncheckedCreateWithoutAnswerOptionInput[]
  connectOrCreate?: Prisma.QuizResponseAnswerCreateOrConnectWithoutAnswerOptionInput | Prisma.QuizResponseAnswerCreateOrConnectWithoutAnswerOptionInput[]
  upsert?: Prisma.QuizResponseAnswerUpsertWithWhereUniqueWithoutAnswerOptionInput | Prisma.QuizResponseAnswerUpsertWithWhereUniqueWithoutAnswerOptionInput[]
  createMany?: Prisma.QuizResponseAnswerCreateManyAnswerOptionInputEnvelope
  set?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  disconnect?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  delete?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  connect?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  update?: Prisma.QuizResponseAnswerUpdateWithWhereUniqueWithoutAnswerOptionInput | Prisma.QuizResponseAnswerUpdateWithWhereUniqueWithoutAnswerOptionInput[]
  updateMany?: Prisma.QuizResponseAnswerUpdateManyWithWhereWithoutAnswerOptionInput | Prisma.QuizResponseAnswerUpdateManyWithWhereWithoutAnswerOptionInput[]
  deleteMany?: Prisma.QuizResponseAnswerScalarWhereInput | Prisma.QuizResponseAnswerScalarWhereInput[]
}

export type QuizResponseAnswerUncheckedUpdateManyWithoutAnswerOptionNestedInput = {
  create?: Prisma.XOR<Prisma.QuizResponseAnswerCreateWithoutAnswerOptionInput, Prisma.QuizResponseAnswerUncheckedCreateWithoutAnswerOptionInput> | Prisma.QuizResponseAnswerCreateWithoutAnswerOptionInput[] | Prisma.QuizResponseAnswerUncheckedCreateWithoutAnswerOptionInput[]
  connectOrCreate?: Prisma.QuizResponseAnswerCreateOrConnectWithoutAnswerOptionInput | Prisma.QuizResponseAnswerCreateOrConnectWithoutAnswerOptionInput[]
  upsert?: Prisma.QuizResponseAnswerUpsertWithWhereUniqueWithoutAnswerOptionInput | Prisma.QuizResponseAnswerUpsertWithWhereUniqueWithoutAnswerOptionInput[]
  createMany?: Prisma.QuizResponseAnswerCreateManyAnswerOptionInputEnvelope
  set?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  disconnect?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  delete?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  connect?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  update?: Prisma.QuizResponseAnswerUpdateWithWhereUniqueWithoutAnswerOptionInput | Prisma.QuizResponseAnswerUpdateWithWhereUniqueWithoutAnswerOptionInput[]
  updateMany?: Prisma.QuizResponseAnswerUpdateManyWithWhereWithoutAnswerOptionInput | Prisma.QuizResponseAnswerUpdateManyWithWhereWithoutAnswerOptionInput[]
  deleteMany?: Prisma.QuizResponseAnswerScalarWhereInput | Prisma.QuizResponseAnswerScalarWhereInput[]
}

export type QuizResponseAnswerCreateNestedManyWithoutResponseInput = {
  create?: Prisma.XOR<Prisma.QuizResponseAnswerCreateWithoutResponseInput, Prisma.QuizResponseAnswerUncheckedCreateWithoutResponseInput> | Prisma.QuizResponseAnswerCreateWithoutResponseInput[] | Prisma.QuizResponseAnswerUncheckedCreateWithoutResponseInput[]
  connectOrCreate?: Prisma.QuizResponseAnswerCreateOrConnectWithoutResponseInput | Prisma.QuizResponseAnswerCreateOrConnectWithoutResponseInput[]
  createMany?: Prisma.QuizResponseAnswerCreateManyResponseInputEnvelope
  connect?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
}

export type QuizResponseAnswerUncheckedCreateNestedManyWithoutResponseInput = {
  create?: Prisma.XOR<Prisma.QuizResponseAnswerCreateWithoutResponseInput, Prisma.QuizResponseAnswerUncheckedCreateWithoutResponseInput> | Prisma.QuizResponseAnswerCreateWithoutResponseInput[] | Prisma.QuizResponseAnswerUncheckedCreateWithoutResponseInput[]
  connectOrCreate?: Prisma.QuizResponseAnswerCreateOrConnectWithoutResponseInput | Prisma.QuizResponseAnswerCreateOrConnectWithoutResponseInput[]
  createMany?: Prisma.QuizResponseAnswerCreateManyResponseInputEnvelope
  connect?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
}

export type QuizResponseAnswerUpdateManyWithoutResponseNestedInput = {
  create?: Prisma.XOR<Prisma.QuizResponseAnswerCreateWithoutResponseInput, Prisma.QuizResponseAnswerUncheckedCreateWithoutResponseInput> | Prisma.QuizResponseAnswerCreateWithoutResponseInput[] | Prisma.QuizResponseAnswerUncheckedCreateWithoutResponseInput[]
  connectOrCreate?: Prisma.QuizResponseAnswerCreateOrConnectWithoutResponseInput | Prisma.QuizResponseAnswerCreateOrConnectWithoutResponseInput[]
  upsert?: Prisma.QuizResponseAnswerUpsertWithWhereUniqueWithoutResponseInput | Prisma.QuizResponseAnswerUpsertWithWhereUniqueWithoutResponseInput[]
  createMany?: Prisma.QuizResponseAnswerCreateManyResponseInputEnvelope
  set?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  disconnect?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  delete?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  connect?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  update?: Prisma.QuizResponseAnswerUpdateWithWhereUniqueWithoutResponseInput | Prisma.QuizResponseAnswerUpdateWithWhereUniqueWithoutResponseInput[]
  updateMany?: Prisma.QuizResponseAnswerUpdateManyWithWhereWithoutResponseInput | Prisma.QuizResponseAnswerUpdateManyWithWhereWithoutResponseInput[]
  deleteMany?: Prisma.QuizResponseAnswerScalarWhereInput | Prisma.QuizResponseAnswerScalarWhereInput[]
}

export type QuizResponseAnswerUncheckedUpdateManyWithoutResponseNestedInput = {
  create?: Prisma.XOR<Prisma.QuizResponseAnswerCreateWithoutResponseInput, Prisma.QuizResponseAnswerUncheckedCreateWithoutResponseInput> | Prisma.QuizResponseAnswerCreateWithoutResponseInput[] | Prisma.QuizResponseAnswerUncheckedCreateWithoutResponseInput[]
  connectOrCreate?: Prisma.QuizResponseAnswerCreateOrConnectWithoutResponseInput | Prisma.QuizResponseAnswerCreateOrConnectWithoutResponseInput[]
  upsert?: Prisma.QuizResponseAnswerUpsertWithWhereUniqueWithoutResponseInput | Prisma.QuizResponseAnswerUpsertWithWhereUniqueWithoutResponseInput[]
  createMany?: Prisma.QuizResponseAnswerCreateManyResponseInputEnvelope
  set?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  disconnect?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  delete?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  connect?: Prisma.QuizResponseAnswerWhereUniqueInput | Prisma.QuizResponseAnswerWhereUniqueInput[]
  update?: Prisma.QuizResponseAnswerUpdateWithWhereUniqueWithoutResponseInput | Prisma.QuizResponseAnswerUpdateWithWhereUniqueWithoutResponseInput[]
  updateMany?: Prisma.QuizResponseAnswerUpdateManyWithWhereWithoutResponseInput | Prisma.QuizResponseAnswerUpdateManyWithWhereWithoutResponseInput[]
  deleteMany?: Prisma.QuizResponseAnswerScalarWhereInput | Prisma.QuizResponseAnswerScalarWhereInput[]
}

export type QuizResponseAnswerCreateWithoutAnswerOptionInput = {
  response: Prisma.QuizResponseCreateNestedOneWithoutAnswersInput
}

export type QuizResponseAnswerUncheckedCreateWithoutAnswerOptionInput = {
  responseId: string
}

export type QuizResponseAnswerCreateOrConnectWithoutAnswerOptionInput = {
  where: Prisma.QuizResponseAnswerWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizResponseAnswerCreateWithoutAnswerOptionInput, Prisma.QuizResponseAnswerUncheckedCreateWithoutAnswerOptionInput>
}

export type QuizResponseAnswerCreateManyAnswerOptionInputEnvelope = {
  data: Prisma.QuizResponseAnswerCreateManyAnswerOptionInput | Prisma.QuizResponseAnswerCreateManyAnswerOptionInput[]
  skipDuplicates?: boolean
}

export type QuizResponseAnswerUpsertWithWhereUniqueWithoutAnswerOptionInput = {
  where: Prisma.QuizResponseAnswerWhereUniqueInput
  update: Prisma.XOR<Prisma.QuizResponseAnswerUpdateWithoutAnswerOptionInput, Prisma.QuizResponseAnswerUncheckedUpdateWithoutAnswerOptionInput>
  create: Prisma.XOR<Prisma.QuizResponseAnswerCreateWithoutAnswerOptionInput, Prisma.QuizResponseAnswerUncheckedCreateWithoutAnswerOptionInput>
}

export type QuizResponseAnswerUpdateWithWhereUniqueWithoutAnswerOptionInput = {
  where: Prisma.QuizResponseAnswerWhereUniqueInput
  data: Prisma.XOR<Prisma.QuizResponseAnswerUpdateWithoutAnswerOptionInput, Prisma.QuizResponseAnswerUncheckedUpdateWithoutAnswerOptionInput>
}

export type QuizResponseAnswerUpdateManyWithWhereWithoutAnswerOptionInput = {
  where: Prisma.QuizResponseAnswerScalarWhereInput
  data: Prisma.XOR<Prisma.QuizResponseAnswerUpdateManyMutationInput, Prisma.QuizResponseAnswerUncheckedUpdateManyWithoutAnswerOptionInput>
}

export type QuizResponseAnswerScalarWhereInput = {
  AND?: Prisma.QuizResponseAnswerScalarWhereInput | Prisma.QuizResponseAnswerScalarWhereInput[]
  OR?: Prisma.QuizResponseAnswerScalarWhereInput[]
  NOT?: Prisma.QuizResponseAnswerScalarWhereInput | Prisma.QuizResponseAnswerScalarWhereInput[]
  responseId?: Prisma.StringFilter<"QuizResponseAnswer"> | string
  answerOptionId?: Prisma.StringFilter<"QuizResponseAnswer"> | string
}

export type QuizResponseAnswerCreateWithoutResponseInput = {
  answerOption: Prisma.AnswerOptionCreateNestedOneWithoutResponsesInput
}

export type QuizResponseAnswerUncheckedCreateWithoutResponseInput = {
  answerOptionId: string
}

export type QuizResponseAnswerCreateOrConnectWithoutResponseInput = {
  where: Prisma.QuizResponseAnswerWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizResponseAnswerCreateWithoutResponseInput, Prisma.QuizResponseAnswerUncheckedCreateWithoutResponseInput>
}

export type QuizResponseAnswerCreateManyResponseInputEnvelope = {
  data: Prisma.QuizResponseAnswerCreateManyResponseInput | Prisma.QuizResponseAnswerCreateManyResponseInput[]
  skipDuplicates?: boolean
}

export type QuizResponseAnswerUpsertWithWhereUniqueWithoutResponseInput = {
  where: Prisma.QuizResponseAnswerWhereUniqueInput
  update: Prisma.XOR<Prisma.QuizResponseAnswerUpdateWithoutResponseInput, Prisma.QuizResponseAnswerUncheckedUpdateWithoutResponseInput>
  create: Prisma.XOR<Prisma.QuizResponseAnswerCreateWithoutResponseInput, Prisma.QuizResponseAnswerUncheckedCreateWithoutResponseInput>
}

export type QuizResponseAnswerUpdateWithWhereUniqueWithoutResponseInput = {
  where: Prisma.QuizResponseAnswerWhereUniqueInput
  data: Prisma.XOR<Prisma.QuizResponseAnswerUpdateWithoutResponseInput, Prisma.QuizResponseAnswerUncheckedUpdateWithoutResponseInput>
}

export type QuizResponseAnswerUpdateManyWithWhereWithoutResponseInput = {
  where: Prisma.QuizResponseAnswerScalarWhereInput
  data: Prisma.XOR<Prisma.QuizResponseAnswerUpdateManyMutationInput, Prisma.QuizResponseAnswerUncheckedUpdateManyWithoutResponseInput>
}

export type QuizResponseAnswerCreateManyAnswerOptionInput = {
  responseId: string
}

export type QuizResponseAnswerUpdateWithoutAnswerOptionInput = {
  response?: Prisma.QuizResponseUpdateOneRequiredWithoutAnswersNestedInput
}

export type QuizResponseAnswerUncheckedUpdateWithoutAnswerOptionInput = {
  responseId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type QuizResponseAnswerUncheckedUpdateManyWithoutAnswerOptionInput = {
  responseId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type QuizResponseAnswerCreateManyResponseInput = {
  answerOptionId: string
}

export type QuizResponseAnswerUpdateWithoutResponseInput = {
  answerOption?: Prisma.AnswerOptionUpdateOneRequiredWithoutResponsesNestedInput
}

export type QuizResponseAnswerUncheckedUpdateWithoutResponseInput = {
  answerOptionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type QuizResponseAnswerUncheckedUpdateManyWithoutResponseInput = {
  answerOptionId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type QuizResponseAnswerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  responseId?: boolean
  answerOptionId?: boolean
  response?: boolean | Prisma.QuizResponseDefaultArgs<ExtArgs>
  answerOption?: boolean | Prisma.AnswerOptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizResponseAnswer"]>

export type QuizResponseAnswerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  responseId?: boolean
  answerOptionId?: boolean
  response?: boolean | Prisma.QuizResponseDefaultArgs<ExtArgs>
  answerOption?: boolean | Prisma.AnswerOptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizResponseAnswer"]>

export type QuizResponseAnswerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  responseId?: boolean
  answerOptionId?: boolean
  response?: boolean | Prisma.QuizResponseDefaultArgs<ExtArgs>
  answerOption?: boolean | Prisma.AnswerOptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizResponseAnswer"]>

export type QuizResponseAnswerSelectScalar = {
  responseId?: boolean
  answerOptionId?: boolean
}

export type QuizResponseAnswerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"responseId" | "answerOptionId", ExtArgs["result"]["quizResponseAnswer"]>
export type QuizResponseAnswerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  response?: boolean | Prisma.QuizResponseDefaultArgs<ExtArgs>
  answerOption?: boolean | Prisma.AnswerOptionDefaultArgs<ExtArgs>
}
export type QuizResponseAnswerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  response?: boolean | Prisma.QuizResponseDefaultArgs<ExtArgs>
  answerOption?: boolean | Prisma.AnswerOptionDefaultArgs<ExtArgs>
}
export type QuizResponseAnswerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  response?: boolean | Prisma.QuizResponseDefaultArgs<ExtArgs>
  answerOption?: boolean | Prisma.AnswerOptionDefaultArgs<ExtArgs>
}

export type $QuizResponseAnswerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuizResponseAnswer"
  objects: {
    response: Prisma.$QuizResponsePayload<ExtArgs>
    answerOption: Prisma.$AnswerOptionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    responseId: string
    answerOptionId: string
  }, ExtArgs["result"]["quizResponseAnswer"]>
  composites: {}
}

export type QuizResponseAnswerGetPayload<S extends boolean | null | undefined | QuizResponseAnswerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuizResponseAnswerPayload, S>

export type QuizResponseAnswerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuizResponseAnswerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuizResponseAnswerCountAggregateInputType | true
  }

export interface QuizResponseAnswerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuizResponseAnswer'], meta: { name: 'QuizResponseAnswer' } }
  /**
   * Find zero or one QuizResponseAnswer that matches the filter.
   * @param {QuizResponseAnswerFindUniqueArgs} args - Arguments to find a QuizResponseAnswer
   * @example
   * // Get one QuizResponseAnswer
   * const quizResponseAnswer = await prisma.quizResponseAnswer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuizResponseAnswerFindUniqueArgs>(args: Prisma.SelectSubset<T, QuizResponseAnswerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuizResponseAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuizResponseAnswerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuizResponseAnswer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuizResponseAnswerFindUniqueOrThrowArgs} args - Arguments to find a QuizResponseAnswer
   * @example
   * // Get one QuizResponseAnswer
   * const quizResponseAnswer = await prisma.quizResponseAnswer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuizResponseAnswerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuizResponseAnswerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizResponseAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuizResponseAnswerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizResponseAnswer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseAnswerFindFirstArgs} args - Arguments to find a QuizResponseAnswer
   * @example
   * // Get one QuizResponseAnswer
   * const quizResponseAnswer = await prisma.quizResponseAnswer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuizResponseAnswerFindFirstArgs>(args?: Prisma.SelectSubset<T, QuizResponseAnswerFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuizResponseAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuizResponseAnswerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizResponseAnswer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseAnswerFindFirstOrThrowArgs} args - Arguments to find a QuizResponseAnswer
   * @example
   * // Get one QuizResponseAnswer
   * const quizResponseAnswer = await prisma.quizResponseAnswer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuizResponseAnswerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuizResponseAnswerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizResponseAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuizResponseAnswerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuizResponseAnswers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseAnswerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuizResponseAnswers
   * const quizResponseAnswers = await prisma.quizResponseAnswer.findMany()
   * 
   * // Get first 10 QuizResponseAnswers
   * const quizResponseAnswers = await prisma.quizResponseAnswer.findMany({ take: 10 })
   * 
   * // Only select the `responseId`
   * const quizResponseAnswerWithResponseIdOnly = await prisma.quizResponseAnswer.findMany({ select: { responseId: true } })
   * 
   */
  findMany<T extends QuizResponseAnswerFindManyArgs>(args?: Prisma.SelectSubset<T, QuizResponseAnswerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizResponseAnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuizResponseAnswer.
   * @param {QuizResponseAnswerCreateArgs} args - Arguments to create a QuizResponseAnswer.
   * @example
   * // Create one QuizResponseAnswer
   * const QuizResponseAnswer = await prisma.quizResponseAnswer.create({
   *   data: {
   *     // ... data to create a QuizResponseAnswer
   *   }
   * })
   * 
   */
  create<T extends QuizResponseAnswerCreateArgs>(args: Prisma.SelectSubset<T, QuizResponseAnswerCreateArgs<ExtArgs>>): Prisma.Prisma__QuizResponseAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuizResponseAnswerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuizResponseAnswers.
   * @param {QuizResponseAnswerCreateManyArgs} args - Arguments to create many QuizResponseAnswers.
   * @example
   * // Create many QuizResponseAnswers
   * const quizResponseAnswer = await prisma.quizResponseAnswer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuizResponseAnswerCreateManyArgs>(args?: Prisma.SelectSubset<T, QuizResponseAnswerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuizResponseAnswers and returns the data saved in the database.
   * @param {QuizResponseAnswerCreateManyAndReturnArgs} args - Arguments to create many QuizResponseAnswers.
   * @example
   * // Create many QuizResponseAnswers
   * const quizResponseAnswer = await prisma.quizResponseAnswer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuizResponseAnswers and only return the `responseId`
   * const quizResponseAnswerWithResponseIdOnly = await prisma.quizResponseAnswer.createManyAndReturn({
   *   select: { responseId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuizResponseAnswerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuizResponseAnswerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizResponseAnswerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuizResponseAnswer.
   * @param {QuizResponseAnswerDeleteArgs} args - Arguments to delete one QuizResponseAnswer.
   * @example
   * // Delete one QuizResponseAnswer
   * const QuizResponseAnswer = await prisma.quizResponseAnswer.delete({
   *   where: {
   *     // ... filter to delete one QuizResponseAnswer
   *   }
   * })
   * 
   */
  delete<T extends QuizResponseAnswerDeleteArgs>(args: Prisma.SelectSubset<T, QuizResponseAnswerDeleteArgs<ExtArgs>>): Prisma.Prisma__QuizResponseAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuizResponseAnswerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuizResponseAnswer.
   * @param {QuizResponseAnswerUpdateArgs} args - Arguments to update one QuizResponseAnswer.
   * @example
   * // Update one QuizResponseAnswer
   * const quizResponseAnswer = await prisma.quizResponseAnswer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuizResponseAnswerUpdateArgs>(args: Prisma.SelectSubset<T, QuizResponseAnswerUpdateArgs<ExtArgs>>): Prisma.Prisma__QuizResponseAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuizResponseAnswerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuizResponseAnswers.
   * @param {QuizResponseAnswerDeleteManyArgs} args - Arguments to filter QuizResponseAnswers to delete.
   * @example
   * // Delete a few QuizResponseAnswers
   * const { count } = await prisma.quizResponseAnswer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuizResponseAnswerDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuizResponseAnswerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizResponseAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseAnswerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuizResponseAnswers
   * const quizResponseAnswer = await prisma.quizResponseAnswer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuizResponseAnswerUpdateManyArgs>(args: Prisma.SelectSubset<T, QuizResponseAnswerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizResponseAnswers and returns the data updated in the database.
   * @param {QuizResponseAnswerUpdateManyAndReturnArgs} args - Arguments to update many QuizResponseAnswers.
   * @example
   * // Update many QuizResponseAnswers
   * const quizResponseAnswer = await prisma.quizResponseAnswer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuizResponseAnswers and only return the `responseId`
   * const quizResponseAnswerWithResponseIdOnly = await prisma.quizResponseAnswer.updateManyAndReturn({
   *   select: { responseId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuizResponseAnswerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuizResponseAnswerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizResponseAnswerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuizResponseAnswer.
   * @param {QuizResponseAnswerUpsertArgs} args - Arguments to update or create a QuizResponseAnswer.
   * @example
   * // Update or create a QuizResponseAnswer
   * const quizResponseAnswer = await prisma.quizResponseAnswer.upsert({
   *   create: {
   *     // ... data to create a QuizResponseAnswer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuizResponseAnswer we want to update
   *   }
   * })
   */
  upsert<T extends QuizResponseAnswerUpsertArgs>(args: Prisma.SelectSubset<T, QuizResponseAnswerUpsertArgs<ExtArgs>>): Prisma.Prisma__QuizResponseAnswerClient<runtime.Types.Result.GetResult<Prisma.$QuizResponseAnswerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuizResponseAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseAnswerCountArgs} args - Arguments to filter QuizResponseAnswers to count.
   * @example
   * // Count the number of QuizResponseAnswers
   * const count = await prisma.quizResponseAnswer.count({
   *   where: {
   *     // ... the filter for the QuizResponseAnswers we want to count
   *   }
   * })
  **/
  count<T extends QuizResponseAnswerCountArgs>(
    args?: Prisma.Subset<T, QuizResponseAnswerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuizResponseAnswerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuizResponseAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseAnswerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuizResponseAnswerAggregateArgs>(args: Prisma.Subset<T, QuizResponseAnswerAggregateArgs>): Prisma.PrismaPromise<GetQuizResponseAnswerAggregateType<T>>

  /**
   * Group by QuizResponseAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizResponseAnswerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuizResponseAnswerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuizResponseAnswerGroupByArgs['orderBy'] }
      : { orderBy?: QuizResponseAnswerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuizResponseAnswerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuizResponseAnswerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuizResponseAnswer model
 */
readonly fields: QuizResponseAnswerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuizResponseAnswer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuizResponseAnswerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  response<T extends Prisma.QuizResponseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuizResponseDefaultArgs<ExtArgs>>): Prisma.Prisma__QuizResponseClient<runtime.Types.Result.GetResult<Prisma.$QuizResponsePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  answerOption<T extends Prisma.AnswerOptionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AnswerOptionDefaultArgs<ExtArgs>>): Prisma.Prisma__AnswerOptionClient<runtime.Types.Result.GetResult<Prisma.$AnswerOptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuizResponseAnswer model
 */
export interface QuizResponseAnswerFieldRefs {
  readonly responseId: Prisma.FieldRef<"QuizResponseAnswer", 'String'>
  readonly answerOptionId: Prisma.FieldRef<"QuizResponseAnswer", 'String'>
}
    

// Custom InputTypes
/**
 * QuizResponseAnswer findUnique
 */
export type QuizResponseAnswerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseAnswer
   */
  select?: Prisma.QuizResponseAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponseAnswer
   */
  omit?: Prisma.QuizResponseAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseAnswerInclude<ExtArgs> | null
  /**
   * Filter, which QuizResponseAnswer to fetch.
   */
  where: Prisma.QuizResponseAnswerWhereUniqueInput
}

/**
 * QuizResponseAnswer findUniqueOrThrow
 */
export type QuizResponseAnswerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseAnswer
   */
  select?: Prisma.QuizResponseAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponseAnswer
   */
  omit?: Prisma.QuizResponseAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseAnswerInclude<ExtArgs> | null
  /**
   * Filter, which QuizResponseAnswer to fetch.
   */
  where: Prisma.QuizResponseAnswerWhereUniqueInput
}

/**
 * QuizResponseAnswer findFirst
 */
export type QuizResponseAnswerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseAnswer
   */
  select?: Prisma.QuizResponseAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponseAnswer
   */
  omit?: Prisma.QuizResponseAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseAnswerInclude<ExtArgs> | null
  /**
   * Filter, which QuizResponseAnswer to fetch.
   */
  where?: Prisma.QuizResponseAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizResponseAnswers to fetch.
   */
  orderBy?: Prisma.QuizResponseAnswerOrderByWithRelationInput | Prisma.QuizResponseAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizResponseAnswers.
   */
  cursor?: Prisma.QuizResponseAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizResponseAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizResponseAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizResponseAnswers.
   */
  distinct?: Prisma.QuizResponseAnswerScalarFieldEnum | Prisma.QuizResponseAnswerScalarFieldEnum[]
}

/**
 * QuizResponseAnswer findFirstOrThrow
 */
export type QuizResponseAnswerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseAnswer
   */
  select?: Prisma.QuizResponseAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponseAnswer
   */
  omit?: Prisma.QuizResponseAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseAnswerInclude<ExtArgs> | null
  /**
   * Filter, which QuizResponseAnswer to fetch.
   */
  where?: Prisma.QuizResponseAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizResponseAnswers to fetch.
   */
  orderBy?: Prisma.QuizResponseAnswerOrderByWithRelationInput | Prisma.QuizResponseAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizResponseAnswers.
   */
  cursor?: Prisma.QuizResponseAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizResponseAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizResponseAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizResponseAnswers.
   */
  distinct?: Prisma.QuizResponseAnswerScalarFieldEnum | Prisma.QuizResponseAnswerScalarFieldEnum[]
}

/**
 * QuizResponseAnswer findMany
 */
export type QuizResponseAnswerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseAnswer
   */
  select?: Prisma.QuizResponseAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponseAnswer
   */
  omit?: Prisma.QuizResponseAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseAnswerInclude<ExtArgs> | null
  /**
   * Filter, which QuizResponseAnswers to fetch.
   */
  where?: Prisma.QuizResponseAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizResponseAnswers to fetch.
   */
  orderBy?: Prisma.QuizResponseAnswerOrderByWithRelationInput | Prisma.QuizResponseAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuizResponseAnswers.
   */
  cursor?: Prisma.QuizResponseAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizResponseAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizResponseAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizResponseAnswers.
   */
  distinct?: Prisma.QuizResponseAnswerScalarFieldEnum | Prisma.QuizResponseAnswerScalarFieldEnum[]
}

/**
 * QuizResponseAnswer create
 */
export type QuizResponseAnswerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseAnswer
   */
  select?: Prisma.QuizResponseAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponseAnswer
   */
  omit?: Prisma.QuizResponseAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseAnswerInclude<ExtArgs> | null
  /**
   * The data needed to create a QuizResponseAnswer.
   */
  data: Prisma.XOR<Prisma.QuizResponseAnswerCreateInput, Prisma.QuizResponseAnswerUncheckedCreateInput>
}

/**
 * QuizResponseAnswer createMany
 */
export type QuizResponseAnswerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuizResponseAnswers.
   */
  data: Prisma.QuizResponseAnswerCreateManyInput | Prisma.QuizResponseAnswerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QuizResponseAnswer createManyAndReturn
 */
export type QuizResponseAnswerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseAnswer
   */
  select?: Prisma.QuizResponseAnswerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponseAnswer
   */
  omit?: Prisma.QuizResponseAnswerOmit<ExtArgs> | null
  /**
   * The data used to create many QuizResponseAnswers.
   */
  data: Prisma.QuizResponseAnswerCreateManyInput | Prisma.QuizResponseAnswerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseAnswerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuizResponseAnswer update
 */
export type QuizResponseAnswerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseAnswer
   */
  select?: Prisma.QuizResponseAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponseAnswer
   */
  omit?: Prisma.QuizResponseAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseAnswerInclude<ExtArgs> | null
  /**
   * The data needed to update a QuizResponseAnswer.
   */
  data: Prisma.XOR<Prisma.QuizResponseAnswerUpdateInput, Prisma.QuizResponseAnswerUncheckedUpdateInput>
  /**
   * Choose, which QuizResponseAnswer to update.
   */
  where: Prisma.QuizResponseAnswerWhereUniqueInput
}

/**
 * QuizResponseAnswer updateMany
 */
export type QuizResponseAnswerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuizResponseAnswers.
   */
  data: Prisma.XOR<Prisma.QuizResponseAnswerUpdateManyMutationInput, Prisma.QuizResponseAnswerUncheckedUpdateManyInput>
  /**
   * Filter which QuizResponseAnswers to update
   */
  where?: Prisma.QuizResponseAnswerWhereInput
  /**
   * Limit how many QuizResponseAnswers to update.
   */
  limit?: number
}

/**
 * QuizResponseAnswer updateManyAndReturn
 */
export type QuizResponseAnswerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseAnswer
   */
  select?: Prisma.QuizResponseAnswerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponseAnswer
   */
  omit?: Prisma.QuizResponseAnswerOmit<ExtArgs> | null
  /**
   * The data used to update QuizResponseAnswers.
   */
  data: Prisma.XOR<Prisma.QuizResponseAnswerUpdateManyMutationInput, Prisma.QuizResponseAnswerUncheckedUpdateManyInput>
  /**
   * Filter which QuizResponseAnswers to update
   */
  where?: Prisma.QuizResponseAnswerWhereInput
  /**
   * Limit how many QuizResponseAnswers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseAnswerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuizResponseAnswer upsert
 */
export type QuizResponseAnswerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseAnswer
   */
  select?: Prisma.QuizResponseAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponseAnswer
   */
  omit?: Prisma.QuizResponseAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseAnswerInclude<ExtArgs> | null
  /**
   * The filter to search for the QuizResponseAnswer to update in case it exists.
   */
  where: Prisma.QuizResponseAnswerWhereUniqueInput
  /**
   * In case the QuizResponseAnswer found by the `where` argument doesn't exist, create a new QuizResponseAnswer with this data.
   */
  create: Prisma.XOR<Prisma.QuizResponseAnswerCreateInput, Prisma.QuizResponseAnswerUncheckedCreateInput>
  /**
   * In case the QuizResponseAnswer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuizResponseAnswerUpdateInput, Prisma.QuizResponseAnswerUncheckedUpdateInput>
}

/**
 * QuizResponseAnswer delete
 */
export type QuizResponseAnswerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseAnswer
   */
  select?: Prisma.QuizResponseAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponseAnswer
   */
  omit?: Prisma.QuizResponseAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseAnswerInclude<ExtArgs> | null
  /**
   * Filter which QuizResponseAnswer to delete.
   */
  where: Prisma.QuizResponseAnswerWhereUniqueInput
}

/**
 * QuizResponseAnswer deleteMany
 */
export type QuizResponseAnswerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizResponseAnswers to delete
   */
  where?: Prisma.QuizResponseAnswerWhereInput
  /**
   * Limit how many QuizResponseAnswers to delete.
   */
  limit?: number
}

/**
 * QuizResponseAnswer without action
 */
export type QuizResponseAnswerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizResponseAnswer
   */
  select?: Prisma.QuizResponseAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizResponseAnswer
   */
  omit?: Prisma.QuizResponseAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizResponseAnswerInclude<ExtArgs> | null
}
