
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  USER: 'USER',
  ADMIN: 'ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const QuestionType = {
  SINGLE_CHOICE: 'SINGLE_CHOICE',
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
  FREE_TEXT: 'FREE_TEXT'
} as const

export type QuestionType = (typeof QuestionType)[keyof typeof QuestionType]


export const Difficulty = {
  JUNIOR: 'JUNIOR',
  MID: 'MID',
  SENIOR: 'SENIOR'
} as const

export type Difficulty = (typeof Difficulty)[keyof typeof Difficulty]


export const QuizSessionStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ABANDONED: 'ABANDONED'
} as const

export type QuizSessionStatus = (typeof QuizSessionStatus)[keyof typeof QuizSessionStatus]


export const CredentialProvider = {
  LOCAL: 'LOCAL',
  GOOGLE: 'GOOGLE',
  GITHUB: 'GITHUB'
} as const

export type CredentialProvider = (typeof CredentialProvider)[keyof typeof CredentialProvider]
