
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Category'
export type * from './models/Question'
export type * from './models/AnswerOption'
export type * from './models/QuizResponse'
export type * from './models/QuizResponseAnswer'
export type * from './models/QuizSession'
export type * from './models/QuizSessionQuestion'
export type * from './commonInputTypes'